// If left empty, everything is allowed, otherwise only whitelisted items will be available
GRLIB_arsenal_weapons = [
"LIB_K98",
"LIB_G43",
"LIB_K98ZF39",
"LIB_MP40",
"LIB_MP44",
"LIB_MG42",
"LIB_M1908",
"LIB_FLARE_PISTOL",
"LIB_PzFaust_30m",
"LIB_RPzB",
"LIB_P38",
"LIB_G3340",
"LIB_P08",
"LIB_GrWr34_Tripod",
"LIB_GrWr34_Barrel",
"LIB_MG34",
"LIB_MG34_PT",
"LIB_Laffete_Tripod",
"LIB_K98_Late",
"LIB_MP38",
"LIB_M1896",
"LIB_WaltherPPK",
"LIB_FG42G2",
"LIB_G41",
"LEN_FG42",   //LEN-Pack
//"LEN_PPK",    //LEN-Pack
//"LEN_P35",    //LEN-Pack
//"LEN_P640b",  //LEN-Pack
"sab_mauser96_handgun", //SABRE-Pack
"fow_w_k98",  //FoW-Mod
"fow_w_mg42", //FoW-Mod
"fow_w_mp40", //FoW-Mod
"fow_w_stg44",//FoW-Mod
"LIB_M31",//IFA3 Liberation-Mod
"LIB_Mg30",    //IFA3 Liberation-Mod
"LIB_MG342",   //IFA3 Liberation-Mod
"ifa3_mg34_tromm",  //IFA3 Liberation-Mod
"lib_Mp18",    //IFA3 Liberation-Mod
"lib_Mp28",    //IFA3 Liberation-Mod
"lib_Mp35",    //IFA3 Liberation-Mod
"Lib_Mp38",    //IFA3 Liberation-Mod
"Lib_Mp41r",   //IFA3 Liberation-Mod
"LIB_kampf_PISTOL", //IFA3 Liberation-Mod
"lib_lp0832",  //IFA3 Liberation-Mod
"lib_lp08",    //IFA3 Liberation-Mod
"lib_p08",//IFA3 Liberation-Mod
"lib_p0832",   //IFA3 Liberation-Mod
"KA_TL_122_flashlight",  //IFA3 Liberation-Mod
"GLIB_GER_PIS625f"    //Geist A3L
];

GRLIB_arsenal_magazines = [
"lib_5Rnd_792x57",
"lib_10Rnd_792x57",
"lib_32Rnd_9x19",
"lib_50Rnd_792x57",
"lib_30Rnd_792x33",
"lib_8Rnd_9x19",
"lib_pwm",
"lib_m39",
"lib_nb39",
"lib_shg24",
"lib_shg24x7",
"LIB_1Rnd_flare_white",
"LIB_1Rnd_flare_red",
"LIB_1Rnd_flare_yellow",
"lib_10Rnd_792x57_sS",
"lib_10Rnd_792x57_SMK",
"lib_10Rnd_792x57_T",
"lib_10Rnd_792x57_T2",
"lib_50Rnd_792x57_sS",
"lib_50Rnd_792x57_SMK",
"lib_5Rnd_792x57_sS",
"lib_5Rnd_792x57_SMK",
"lib_5Rnd_792x57_t",
"LIB_1Rnd_RPzB",
"LIB_1Rnd_PzFaust_30m",
"1Rnd_LIB_PzFaust_30m",
"LIB_shumine_42_MINE_mag",
"LIB_1Rnd_flare_green",
"LIB_SMI_35_MINE_mag",
"LIB_SMI_35_1_MINE_mag",
"LIB_Ladung_Small_MINE_mag",
"LIB_Ladung_Big_MINE_mag",
"LIB_STMI_MINE_mag",
"LIB_TM44_MINE_mag",
"LIB_TMI_42_MINE_mag",
"LIB_Ladung_PM_MINE_mag",
"LIB_MARKER_MINE_mag",
"LIB_1Rnd_G_PZGR_30",
"LIB_1Rnd_G_PZGR_40",
"LIB_1Rnd_G_SPRGR_30",
"LIB_1rnd_81mmHE_GRWR34",
"LIB_81mm_GRWR34_SmokeShell",
"LIB_8Rnd_9x19_P08",
"LIB_100Rnd_792x57",
"LIB_50Rnd_792x57",
"LIB_75Rnd_792x57",
"LIB_50Rnd_792x57_SMK",
"LIB_50Rnd_792x57_sS",
"LIB_6Rnd_763x25",
"LIB_7Rnd_9x19",
"LIB_20Rnd_792x57",
"LIB_10Rnd_792x57_clip",
"LEN_20Rnd_792x57", //LEN-Pack
"LEN_7Rnd_765x17",  //LEN-Pack
"lib_8Rnd_9x19",    //LEN-Pack
"LEN_13Rnd_9x19",   //LEN-Pack
"sab_wwiplanes_6rnd_mauser_mag",   //SABRE-Pack
"fow_5Rnd_792x57", //FoW-Mod
"fow_50Rnd_792x57",//FoW-Mod
"fow_32Rnd_9x19_mp40",  //FoW-Mod
"fow_30Rnd_792x33",//FoW-Mod
"fow_e_m24K_spli", //FoW-Mod
"fow_e_m24_at",    //FoW-Mod
"fow_e_m24_spli",  //FoW-Mod
"fow_e_m24",  //FoW-Mod
"fow_e_m24K", //FoW-Mod
"lib_25Rnd_8x56",   //IFA3 Liberation-Mod
"lib_30Rnd_792x57", //IFA3 Liberation-Mod
"lib_30Rnd_792x57_ss",   //IFA3 Liberation-Mod
"lib_30Rnd_792x57_smk",  //IFA3 Liberation-Mod
"lib_75Rnd_792x57_ss",   //IFA3 Liberation-Mod
"lib_75Rnd_792x57_SMK",  //IFA3 Liberation-Mod
"lib_32Rnd_9x19_MP18",   //IFA3 Liberation-Mod
"lib_32Rnd_9x19_MP28",   //IFA3 Liberation-Mod
"lib_32Rnd_9x19_MP35",   //IFA3 Liberation-Mod
"lib_m39_pist",//IFA3 Liberation-Mod
"LIB_7Rnd_45ACP"    //Geist A3L
];

GRLIB_arsenal_items = [
"FirstAidKit",
"LIB_GER_ItemWatch",
"LIB_GER_ItemCompass_deg",
"LIB_Binocular_GER",
"U_LIB_GER_Funker",
"ItemRadio",
"U_LIB_GER_Gefreiter",
"U_LIB_GER_MG_schutze",
"ItemMap",
"ItemCompass",
"U_LIB_GER_Leutnant",
"U_LIB_GER_Art_leutnant",
"H_LIB_GER_LW_PilotHelmet",
"U_LIB_GER_Medic",
"U_LIB_GER_Oberleutnant",
"U_LIB_GER_Oberschutze",
"U_LIB_GER_Oberst",
"U_LIB_GER_Officer_camo",
"U_LIB_GER_LW_pilot",
"U_LIB_GER_Pionier",
"LIB_ToolKit",
"U_LIB_GER_Recruit",
"U_LIB_GER_Schutze",
"U_LIB_GER_Art_schutze",
"V_LIB_GER_SniperBelt",
"U_LIB_GER_Spg_crew_private",
"U_LIB_GER_Spg_crew_leutnant",
"U_LIB_GER_Spg_crew_unterofficer",
"H_LIB_GER_TankPrivateCap",
"U_LIB_GER_Tank_crew_leutnant",
"U_LIB_GER_Tank_crew_unterofficer",
"H_LIB_GER_TankOfficerCap",
"U_LIB_GER_Soldier_camo",
"ItemWatch",
"U_LIB_GER_Unterofficer",
"U_LIB_GER_Art_unterofficer",
"Medikit",
"H_LIB_GER_Cap",
"V_LIB_GER_FieldOfficer",
"H_LIB_GER_Helmet",
"H_LIB_GER_HelmetCamo",
"H_LIB_GER_HelmetCamo3",
"H_LIB_GER_Helmet_Glasses",
"H_LIB_GER_Helmet_Medic",
"H_LIB_GER_Helmet_os",
"H_LIB_GER_Helmet_os_painted",
"H_LIB_GER_HelmetCamo4",
"H_LIB_GER_HelmetUtility",
"H_LIB_GER_HelmetUtility_Grass",
"H_LIB_GER_HelmetUtility_Oak",
"H_HeadBandage_bloody_F",
"H_HeadBandage_stained_F",
"H_HeadBandage_clean_F",
"V_LIB_GER_OfficerBelt",
"H_LIB_GER_OfficerCap",
"V_LIB_GER_OfficerVest",
"V_LIB_GER_PrivateBelt",
"V_LIB_GER_VestUnterofficer",
"V_LIB_GER_VestG43",
"V_LIB_GER_VestKar98",
"V_LIB_GER_VestMG",
"V_LIB_GER_VestMP40",
"V_LIB_GER_VestSTG",
"ToolKit",
"H_LIB_GER_SPGPrivateCap",
"U_LIB_GER_Scharfschutze",
"U_LIB_GER_Soldier2",
"U_LIB_GER_Soldier3",
"U_LIB_GER_Soldier_camo2",
"U_LIB_GER_Soldier_camo3",
"U_LIB_GER_Soldier_camo4",
"U_LIB_GER_Soldier_camo5",
"V_LIB_GER_PioneerVest",
"H_LIB_GER_TankPrivateCap2",
"H_LIB_GER_TankOfficerCap2",
"H_LIB_GER_HelmetCamo2",
"H_LIB_GER_Helmet_net",
"H_LIB_GER_Helmet_ns",
"H_LIB_GER_Helmet_painted",
"H_LIB_GER_Helmet_net_painted",
"H_LIB_GER_Helmet_ns_painted",
"H_LIB_GER_Ushanka",
"G_LIB_Binoculars",
"G_LIB_Dienst_Brille",
"G_LIB_Dienst_Brille2",
"G_LIB_Dust_Goggles",
"G_LIB_GER_Gloves1",
"G_LIB_GER_Gloves2",
"G_LIB_GER_Gloves3",
"G_LIB_GER_Gloves4",
"G_LIB_Watch1",
"G_LIB_Watch2",
"LIB_ACC_K98_Bayo",
"G_LIB_Headwrap",
"G_LIB_Headwrap_gloves",
"LIB_ACC_GW_SB_Empty",
"G_LIB_Scarf2_B",
"G_LIB_Scarf2_G",
"G_LIB_Scarf_B",
"G_LIB_Scarf_G",
"U_LIB_FJS_Soldier",
"U_LIB_FJS_Soldier_camo",
"U_LIB_FJS_Soldier_dak",
"U_LIB_FJS_Soldier_dak_camo",
"V_LIB_GER_FJS_VestKar98",
"V_LIB_GER_FJS_VestKar98_DAK",
"V_LIB_GER_FJS_VestKar98_Camo",
"H_LIB_GER_FJS_M38_Helmet",
"H_LIB_GER_FJS_M38_Helmet_os",
"H_LIB_GER_FJS_M38_Helmet_Cover",
"H_LIB_GER_FJS_M38_Helmet_DAK",
"H_LIB_GER_FJS_M38_Helmet_grey_os",
"H_LIB_GER_FJS_M38_Helmet_grey",
"H_LIB_GER_FJS_M44_Helmet",
"H_LIB_GER_FJS_M44_Helmet_Medic",
"H_LIB_GER_FJS_M44_Helmet_os",
"H_LIB_GER_FJS_M44_HelmetCamo1",
"H_LIB_GER_FJS_M44_HelmetCamo2",
"H_LIB_GER_FJS_M44_HelmetUtility",
"optic_zf41",        //IFA3 Liberation
"Len_ACC_FG42_Bayo",   //LEN-Pack
"sab_wwiplanes_pilot_holster",   //SABRE-Pack
"U_LEN_SS_Schutze",  //LEN SS-Pack
"U_LEN_SS_Schutze2", //LEN SS-Pack
"U_LEN_SS_Schutze3", //LEN SS-Pack
"U_LEN_SS_Recruit",  //LEN SS-Pack
"U_LEN_SS_Oberschutze",   //LEN SS-Pack
"U_LEN_SS_Sturmmann",//LEN SS-Pack
"U_LEN_SS_Medic",    //LEN SS-Pack
"U_LEN_SS_Medic2",   //LEN SS-Pack
"U_LEN_SS_MG_schutze",    //LEN SS-Pack
"U_LEN_SS_Sapper_Gefr",   //LEN SS-Pack
"U_LEN_SS_Driver",   //LEN SS-Pack
"U_LEN_SS_SecLeader",//LEN SS-Pack
"U_LEN_SS_Untersturmfuhrer",   //LEN SS-Pack
"U_LEN_SS_Oberfuhrer",    //LEN SS-Pack
"U_LEN_SS_Scharfschutze", //LEN SS-Pack
"U_LEN_SS_Soldier_camo",  //LEN SS-Pack
"U_LEN_SS_unequip_camo",  //LEN SS-Pack
"U_LEN_SS_SecLeader_camo",//LEN SS-Pack
"U_LEN_SS_PlatLeader_camo",    //LEN SS-Pack
"U_LEN_SS_Oberschutze_camo",   //LEN SS-Pack
"U_LEN_SS_Soldier_camo_E",//LEN SS-Pack
"U_LEN_SS_Soldier_camo2_E",    //LEN SS-Pack
"U_LEN_SS_SecLeader_camo_E",   //LEN SS-Pack
"U_LEN_SS_Soldier_camo_W",//LEN SS-Pack
"U_LEN_SS_Soldier2_camo_W",    //LEN SS-Pack
"U_LEN_SS_Soldier3_camo_W",    //LEN SS-Pack
"U_LEN_SS_Soldier4_camo_W",    //LEN SS-Pack
"U_LEN_SS_Soldier5_camo_W",    //LEN SS-Pack
"U_LEN_SS_Soldier6_camo_W",    //LEN SS-Pack
"U_LEN_SS_Soldier7_camo_W",    //LEN SS-Pack
"U_LEN_SS_Scharfschutze_W",    //LEN SS-Pack
"U_LEN_SS_Scharfschutze2_W",   //LEN SS-Pack
"U_LEN_SS_SecLeader_camo_w",   //LEN SS-Pack
"U_LEN_SS_Tank_crew_private",  //LEN SS-Pack
"U_LEN_SS_Tank_crew_unterofficer",  //LEN SS-Pack
"U_LEN_SS_Tank_crew_lieutnant",//LEN SS-Pack
"U_LEN_SS_Tank_crew_private_camo",  //LEN SS-Pack
"U_LEN_SS_Tank_crew_unterofficer_camo",  //LEN SS-Pack
"U_LEN_SS_Tank_crew_lieutnant_camo",//LEN SS-Pack
"U_LEN_SS_SPG_crew_private_camo",   //LEN SS-Pack
"H_LEN_SS_HelmetCamo",    //LEN SS-Pack
"H_LEN_SS_HelmetCamo2",   //LEN SS-Pack
"H_LEN_SS_HelmetCamo3",   //LEN SS-Pack
"H_LEN_SS_HelmetCamo_W",  //LEN SS-Pack
"H_LEN_SS_Helmet",   //LEN SS-Pack
"H_LEN_SS_Helmet_net",    //LEN SS-Pack
"H_LEN_SS_Helmet_ns",//LEN SS-Pack
"H_LEN_SS_Helmet_paint",  //LEN SS-Pack
"H_LEN_SS_Helmet_net_paint",   //LEN SS-Pack
"H_LEN_SS_Helmet_ns_paint",    //LEN SS-Pack
"H_LEN_SS_Helmet_Medic",  //LEN SS-Pack
"H_LEN_SS_Helmet_ns_Medic",    //LEN SS-Pack
"H_LEN_SS_Helmet_w", //LEN SS-Pack
"H_LEN_SS_Helmet_net_w",  //LEN SS-Pack
"H_LEN_SS_Helmet_ns_w",   //LEN SS-Pack
"H_LEN_SS_Helmet_E", //LEN SS-Pack
"H_LEN_SS_Helmet_net_E",  //LEN SS-Pack
"H_LEN_SS_Helmet_ns_E",   //LEN SS-Pack
"H_LEN_SS_OfficerCap",    //LEN SS-Pack
"H_LEN_SS_OfficerCap_Artillery",    //LEN SS-Pack
"H_LEN_SS_OfficerCap_Motorized",    //LEN SS-Pack
"H_LEN_SS_Cap", //LEN SS-Pack
"H_LEN_SS_Fieldcap", //LEN SS-Pack
"H_LEN_SS_Fieldcap2",//LEN SS-Pack
"H_LEN_SS_Fieldcap_W",    //LEN SS-Pack
"H_LEN_SS_Handschar1",    //LEN SS-Pack
"H_LEN_SS_Handschar2",    //LEN SS-Pack
"H_LEN_SS_TankOfficerCap",//LEN SS-Pack
"H_LEN_SS_TankOfficerCap2",    //LEN SS-Pack
"H_LEN_SS_TankPrivateCap",//LEN SS-Pack
"H_LEN_SS_TankPrivateCap2",    //LEN SS-Pack
"H_LEN_SS_SPGPrivateCap", //LEN SS-Pack
"H_LEN_SS_Cap_Radio",//LEN SS-Pack
"G_LEN_Scarf_Camo",  //LEN SS-Pack
"G_LEN_Scarf2_Camo", //LEN SS-Pack
"V_LEN_SS_VestMP40", //LEN SS-Pack
"V_LEN_SS_VestSTG",  //LEN SS-Pack
"V_LEN_SS_VestKar98",//LEN SS-Pack
"V_LEN_SS_VestG43",  //LEN SS-Pack
"V_LEN_SS_SniperBelt",    //LEN SS-Pack
"V_LEN_SS_VestMG",   //LEN SS-Pack
"V_LEN_SS_VestUnterofficer",   //LEN SS-Pack
"V_LEN_SS_FieldOfficer",  //LEN SS-Pack
"V_LEN_SS_OfficerVest",   //LEN SS-Pack
"V_LEN_SS_OfficerBelt",   //LEN SS-Pack
"V_LEN_SS_PrivateBelt",   //LEN SS-Pack
"V_LEN_SS_PioneerVest",   //LEN SS-Pack
"V_LEN_SS_TankPrivateBelt",    //LEN SS-Pack
"fow_u_ger_fall_03_corporal",//FoW-Mod
"fow_u_ger_fall_03_lance_corporal",    //FoW-Mod
"fow_u_ger_fall_03_private", //FoW-Mod
"fow_u_ger_fall_03_sergeant",//FoW-Mod
"fow_u_ger_fall_02_corporal",//FoW-Mod
"fow_u_ger_fall_02_lance_corporal",    //FoW-Mod
"fow_u_ger_fall_02_private", //FoW-Mod
"fow_u_ger_fall_02_sergeant",//FoW-Mod
"fow_u_ger_fall_01_corporal",//FoW-Mod
"fow_u_ger_fall_01_lance_corporal",    //FoW-Mod
"fow_u_ger_fall_01_private", //FoW-Mod
"fow_u_ger_fall_01_sergeant",//FoW-Mod
"fow_u_ger_m43_01_frag_private",  //FoW-Mod
"fow_u_ger_m43_01_corporal", //FoW-Mod
"fow_u_ger_m43_01_lance_corporal",//FoW-Mod
"fow_u_ger_m43_01_private",  //FoW-Mod
"fow_u_ger_m43_02_corporal", //FoW-Mod
"fow_u_ger_m43_02_lance_corporal",//FoW-Mod
"fow_u_ger_m43_02_private",  //FoW-Mod
"fow_v_fall_bandoleer", //FoW-Mod
"fow_v_heer_g43",  //FoW-Mod
"fow_v_heer_k98",  //FoW-Mod
"fow_v_heer_k98_ass",   //FoW-Mod
"fow_v_heer_k98_bayo",  //FoW-Mod
"fow_v_heer_k98_light", //FoW-Mod
"fow_v_heer_mg",   //FoW-Mod
"fow_v_heer_mp40", //FoW-Mod
"fow_v_heer_mp40_nco",  //FoW-Mod
"fow_v_heer_mp44", //FoW-Mod
"fow_v_heer_p38",  //FoW-Mod
"fow_h_ger_feldmutze",  //FoW-Mod
"fow_h_ger_m38_feldmutze",   //FoW-Mod
"fow_h_ger_m40_fall_01",//FoW-Mod
"fow_h_ger_m40_fall_01_camo",//FoW-Mod
"fow_h_ger_m40_heer_01",//FoW-Mod
"fow_h_ger_m40_heer_camo",   //FoW-Mod
"fow_h_ger_m40_luftwaffe_01",//FoW-Mod
"fow_h_ger_m40_luftwaffe_02",//FoW-Mod
"tf_anprc148jem_3",   //TFAR
"tf_anprc148jem_4",   //TFAR
"tf_anprc152_1", //TFAR
"tf_fadak_1",    //TFAR
"tf_pnr1000a_1", //TFAR
"tf_rf7800str",  //TFAR
"ACE_atropine",                   //ACE
"ACE_fieldDressing",              //ACE
"ACE_elasticBandage",             //ACE
"ACE_quikclot",                   //ACE
"ACE_bloodIV",                    //ACE
"ACE_bloodIV_500",                //ACE
"ACE__bloodIV_250",               //ACE
"ACE_bodyBag",                    //ACE
"ACE_bodyBagObject",              //ACE
"ACE_epinephrine",                //ACE
"ACE_morphine",                   //ACE
"ACE_packingBandage",             //ACE
"ACE_personalAidKit",             //ACE
"ACE_plasmaIV",                   //ACE
"ACE_plasmaIV_500",               //ACE
"ACE_plasmaIV_250",               //ACE
"ACE_salineIV",                   //ACE
"ACE_salineIV_500",               //ACE
"ACE_saline_250",                 //ACE
"ACE_surgicalKit",                //ACE
"ACE_tourniquet",                 //ACE
"U_LIB_GER_Subofficer_camo_Flak142v00pFwMp40",
"U_LIB_GER_Subofficer_camo_Flak142v00pFw2Mp40",
"U_LIB_GER_Soldier_camo_Flak142v00pSchK98",
"U_LIB_GER_Soldier_camo_Flak142v00pSch2K98",
"U_LIB_GER_Soldier_camo_Flak142v00pGefrG43",
"U_LIB_GER_Soldier_camo_Flak142v00pGefr2G43",
"U_LIB_GER_Soldier_camo_Flak142v00pGefr6yMp40",
"U_LIB_GER_Soldier_camo_Flak142v00pGefr6y2Mp40",
"U_LIB_GER_Soldier_camo_Flak142v00pOschG43",
"U_LIB_GER_Soldier_camo_Flak142v00pOsch2G43",
"U_LIB_GER_Soldier_camo_Flak142v00pOgefrG43",
"U_LIB_GER_Soldier_camo_Flak142v00pOgefr2G43",
"U_LIB_GER_Soldier_camo_Flak142v00pStgefrMp40",
"U_LIB_GER_Soldier_camo_Flak142v00pStgefr2Mp40",
"U_LIB_GER_Subofficer_camo_Flak142v00pUffzMp40",
"U_LIB_GER_Subofficer_camo_Flak142v00pUffz2Mp40",
"U_LIB_GER_Soldier_camo_Flak143v00pSchK98",
"U_LIB_GER_Soldier_camo_Flak143v00pSch2K98",
"U_LIB_GER_Soldier_camo_Flak143v00pGefrSantG43",
"U_LIB_GER_Soldier_camo_Flak143v00pGefrMp40",
"U_LIB_GER_Soldier_camo_Flak143v00pGefrSant2G43",
"U_LIB_GER_Soldier_camo_Flak143v00pGefr2Mp40",
"U_LIB_GER_Soldier_camo_Flak143v00pGefr6yG43",
"U_LIB_GER_Soldier_camo_Flak143v00pGefr6y2G43",
"U_LIB_GER_Soldier_camo_Flak143v00pHptgefrMp40",
"U_LIB_GER_Soldier_camo_Flak143v00pHptgefr2Mp40",
"U_LIB_GER_Officer_camo_Flak143v00pLtMp40",
"U_LIB_GER_Subofficer_camo_Flak143v00pOfwMp40",
"U_LIB_GER_Subofficer_camo_Flak143v00pOfw2Mp40",
"U_LIB_GER_Soldier_camo_Flak143v00pOschG43",
"U_LIB_GER_Soldier_camo_Flak143v00pOsch2G43",
"U_LIB_GER_Soldier_camo_Flak143v00pOgefrMp40",
"U_LIB_GER_Soldier_camo_Flak143v00pOgefr2Mp40",
"U_LIB_GER_Subofficer_camo_Flak143v00pUfwMp40",
"U_LIB_GER_unterofficer_FlakFwMp40",
"U_LIB_GER_rifleman_FlakSchK98",
"U_LIB_GER_rifleman_FlakSchBK98",
"U_LIB_GER_rifleman_FlakSchCK98",
"U_LIB_GER_rifleman_FlakSchDK98",
"U_LIB_GER_smgunner_FlakGefrMp40",
"U_LIB_GER_smgunner_FlakGefr6yMp40",
"U_LIB_GER_Officer_FlakHptmMp40",
"U_LIB_GER_Officer_FlakLtMp40",
"U_LIB_GER_unterofficer_FlakOfwMp40",
"U_LIB_GER_ober_rifleman_FlakOschG43",
"U_LIB_GER_ober_rifleman_FlakOschBG43",
"U_LIB_GER_ober_rifleman_FlakOschCG43",
"U_LIB_GER_ober_rifleman_FlakOschDG43",
"U_LIB_GER_smgunner_FlakOgefrMp40",
"U_LIB_GER_Officer_FlakOltMp40",
"U_LIB_GER_medic_FlakK98",
"U_LIB_GER_unterofficer_FlakStfwMp40",
"U_LIB_GER_smgunner_FlakStgefrMp40",
"U_LIB_GER_unterofficer_FlakUfwMp40",
"U_LIB_GER_unterofficer_FlakUffzMp40",
"U_LIB_GER_Subofficer_camo_FSJ291v00pFwMp40",
"U_LIB_GER_Soldier_camo_FSJ291v00pSchSantK98",
"U_LIB_GER_Soldier_camo_FSJ291v00pSchK98",
"U_LIB_GER_Soldier_camo_FSJ291v00pGefrSantG43",
"U_LIB_GER_Soldier_camo_FSJ291v00pGefrMp40",
"U_LIB_GER_Soldier_camo_FSJ291v00pGefr6yMp40",
"U_LIB_GER_Soldier_camo_FSJ291v00pHptgefrMp40",
"U_LIB_GER_Officer_camo_FSJ291v00pHptmMp40",
"U_LIB_GER_Officer_camo_FSJ291v00pLtMp40",
"U_LIB_GER_Subofficer_camo_FSJ291v00pOfwMp40",
"U_LIB_GER_Soldier_camo_FSJ291v00pOschG43",
"U_LIB_GER_Soldier_camo_FSJ291v00pOgefrMp40",
"U_LIB_GER_Officer_camo_FSJ291v00pOltMp40",
"U_LIB_GER_Subofficer_camo_FSJ291v00pStfwMp40",
"U_LIB_GER_Soldier_camo_FSJ291v00pStgefrMp40",
"U_LIB_GER_Subofficer_camo_FSJ291v00pUfwMp40",
"U_LIB_GER_Subofficer_camo_FSJ291v00pUfwMp40",
"U_LIB_GER_Subofficer_camo_FSJ291v00pUffzMp40",
"U_LIB_GER_Soldier_camo_FSJ292v00pSchK98",
"U_LIB_GER_Soldier_camo_FSJ292v00pGefrSantG43",
"U_LIB_GER_Soldier_camo_FSJ292v00pGefr6yMp40",
"U_LIB_GER_Soldier_camo_FSJ292v00pHptgefrMp40",
"U_LIB_GER_Officer_camo_FSJ292v00pHptmMp40",
"U_LIB_GER_Officer_camo_FSJ292v00pLtMp40",
"U_LIB_GER_Subofficer_camo_FSJ292v00pOfwMp40",
"U_LIB_GER_Soldier_camo_FSJ292v00pOschG43",
"U_LIB_GER_Soldier_camo_FSJ292v00pOgefrG43",
"U_LIB_GER_Soldier_camo_FSJ292v00pStgefrStg44",
"U_LIB_GER_Subofficer_camo_FSJ292v00pUfwMp40",
"U_LIB_GER_Subofficer_camo_FSJ292v00pUffzMp40",
"U_LIB_GER_Subofficer_camo_FSJ293v00pFwMp40",
"U_LIB_GER_Soldier_camo_FSJ293v00pSchSantK98",
"U_LIB_GER_Soldier_camo_FSJ293v00pSchK98",
"U_LIB_GER_Soldier_camo_FSJ293v00pGefrMp40",
"U_LIB_GER_Soldier_camo_FSJ293v00pGefr6yG43",
"U_LIB_GER_Soldier_camo_FSJ293v00pOschStg44",
"U_LIB_GER_Soldier_camo_FSJ293v00pOgefrMp40",
"U_LIB_GER_Officer_camo_FSJ293v00pOltMp40",
"U_LIB_GER_Subofficer_camo_FSJ293v00pStfwMp40",
"U_LIB_GER_Soldier_camo_FSJ293v00pStgefrMp40",
"U_LIB_GER_Subofficer_camo_FSJ293v00pUfwStg44",
"U_LIB_GER_Subofficer_camo_FSJ293v00pUffzSantG43",
"U_LIB_GER_Subofficer_camo_FSJ293v00pUffzStg44",
"U_LIB_GER_Officer_FSJ291v00pHptmMp40",
"U_LIB_GER_Officer_FSJ291v00pLtMp40",
"U_LIB_GER_Officer_FSJ291v00pOltMp40",
"U_LIB_GER_Officer_FSJ292v00pOltMp40",
"U_LIB_GER_Officer_FSJ293v00pHptmMp40",
"U_LIB_GER_Officer_FSJ293v00pLtMp40",
"U_LIB_GER_unterofficer_HeerFldGdrFwMp40",
"U_LIB_GER_smgunner_HeerFldGdrGefrMp40",
"U_LIB_GER_smgunner_HeerFldGdrGefr6yMp40",
"U_LIB_GER_smgunner_HeerFldGdrGefr6yMp40",
"U_LIB_GER_Officer_HeerFldGdrLtMp40",
"U_LIB_GER_unterofficer_HeerFldGdrOfwMp40",
"U_LIB_GER_smgunner_HeerFldGdrOgefrMp40",
"U_LIB_GER_Officer_HeerFldGdrOltMp40",
"U_LIB_GER_ober_rifleman_HeerFldGdrOschG43",
"U_LIB_GER_rifleman_HeerFldGdrSchK98",
"U_LIB_GER_unterofficer_HeerFldGdrUfwMp40",
"U_LIB_GER_unterofficer_HeerFldGdrUffzMp40",
"U_LIB_GER_unterofficer_HeerGrsDldFwMp40",
"U_LIB_GER_unterofficer_HeerGrsDldFw12Mp40",
"U_LIB_GER_unterofficer_HeerGrsDldFw2Mp40",
"U_LIB_GER_smgunner_HeerGrsDldGefrMp40",
"U_LIB_GER_smgunner_HeerGrsDldGefr2Mp40",
"U_LIB_GER_smgunner_HeerGrsDldGefr6yMp40",
"U_LIB_GER_smgunner_HeerGrsDldGefr6y2Mp40",
"U_LIB_GER_Officer_HeerGrsDldHauptMp40",
"U_LIB_GER_OfficerArzt_HeerGrsDldLtMp40",
"U_LIB_GER_Officer_HeerGrsDldLtMp40",
"U_LIB_GER_unterofficer_HeerGrsDldOfwMp40",
"U_LIB_GER_unterofficer_HeerGrsDldOfw12Mp40",
"U_LIB_GER_unterofficer_HeerGrsDldOfw2Mp40",
"U_LIB_GER_smgunner_HeerGrsDldOgefrMp40",
"U_LIB_GER_smgunner_HeerGrsDldOgefr2Mp40",
"U_LIB_GER_Officer_HeerGrsDldOltMp40",
"U_LIB_GER_ober_rifleman_HeerGrsDldOschG43",
"U_LIB_GER_ober_rifleman_HeerGrsDldOsch2G43",
"U_LIB_GER_Officer_HeerGrsDldObstMp40",
"U_LIB_GER_medic_HeerGrsDldK98",
"U_LIB_GER_medic_HeerGrsDld12K98",
"U_LIB_GER_rifleman_HeerGrsDldSchK98",
"U_LIB_GER_rifleman_HeerGrsDldSch12K98",
"U_LIB_GER_rifleman_HeerGrsDldSch13K98",
"U_LIB_GER_rifleman_HeerGrsDldSch2K98",
"U_LIB_GER_unterofficer_HeerGrsDldStfwMp40",
"U_LIB_GER_smgunner_HeerGrsDldStgefrMp40",
"U_LIB_GER_unterofficer_HeerGrsDldUfwMp40",
"U_LIB_GER_unterofficer_HeerGrsDldUfw12Mp40",
"U_LIB_GER_unterofficer_HeerGrsDldUfw2Mp40",
"U_LIB_GER_unterofficer_HeerGrsDldUffzMp40",
"U_LIB_GER_unterofficer_HeerGrsDldUffz12Mp40",
"U_LIB_GER_unterofficer_HeerGrsDldUffz2Mp40",
"U_LIB_GER_unterofficer_HeerGrsDld00v142pFw12Mp40",
"U_LIB_GER_rifleman_HeerGrsDld00v142pSch12K98",
"U_LIB_GER_rifleman_HeerGrsDld00v142pSch13K98",
"U_LIB_GER_unterofficer_HeerGrsDld00v142pUfw13Mp40",
"U_LIB_GER_unterofficer_HeerGrsDld00v143pFw13Mp40",
"U_LIB_GER_rifleman_HeerGrsDld00v143pSch12K98",
"U_LIB_GER_rifleman_HeerGrsDld00v143pSch13K98",
"U_LIB_GER_unterofficer_HeerGrsDld00v143pUffz12Mp40",
"U_LIB_GER_rifleman_HeerGrsDld00v144pSch12K98",
"U_LIB_GER_rifleman_HeerGrsDld00v144pSch13K98",
"U_LIB_GER_unterofficer_HeerGrsDld00v144pUfw12Mp40",
"U_LIB_GER_unterofficer_HeerGrsDld00v144pUffz13Mp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerGrsDld0sv0spbcFwMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerGrsDld0sv0spbcGefrMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerGrsDld0sv0spbcGefr6yMp40",
"U_LIB_GER_Sturm_Crew_Officer_HeerGrsDld0sv0spbcHptmMp40",
"U_LIB_GER_Sturm_Crew_Officer_HeerGrsDld0sv0spbcLtMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerGrsDld0sv0spbcOfwMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerGrsDld0sv0spbcOgefrMp40",
"U_LIB_GER_Sturm_Crew_Officer_HeerGrsDld0sv0spbcOltMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerGrsDld0sv0spbcOschMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerGrsDld0sv0spbcSchMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerGrsDld0sv0spbcStfwMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerGrsDld0sv0spbcStgefrMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerGrsDld0sv0spbcUfwMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerGrsDld0sv0spbcUffzMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpbcFwMp40",
"U_LIB_GER_Tank_Crew_Private_HeerGrsDld0tv0tpbcGefrMp40",
"U_LIB_GER_Tank_Crew_Private_HeerGrsDld0tv0tpbcGefr6yMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerGrsDld0tv0tpbcHptmMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerGrsDld0tv0tpbcLtMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpbcOfwMp40",
"U_LIB_GER_Tank_Crew_Private_HeerGrsDld0tv0tpbcOgefrMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerGrsDld0tv0tpbcOltMp40",
"U_LIB_GER_Tank_Crew_Private_HeerGrsDld0tv0tpbcOschMp40",
"U_LIB_GER_Tank_Crew_Private_HeerGrsDld0tv0tpbcSchMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpbcStfwMp40",
"U_LIB_GER_Tank_Crew_Private_HeerGrsDld0tv0tpbcStgefrMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpbcUfwMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpbcUffzMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpncFwMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerGrsDld0tv0tpncHptmMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerGrsDld0tv0tpncLtMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpncOfwMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerGrsDld0tv0tpncOltMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerGrsDld0tv0tpncStfwMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrFwMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrFw12Mp40",
"U_LIB_GER_unterofficer_HeerPzrLhrFw2Mp40",
"U_LIB_GER_smgunner_HeerPzrLhrGefrMp40",
"U_LIB_GER_smgunner_HeerPzrLhrGefr2Mp40",
"U_LIB_GER_smgunner_HeerPzrLhrGefr6y2Mp40",
"U_LIB_GER_smgunner_HeerPzrLhrGefr6yMp40",
"U_LIB_GER_Officer_HeerPzrLhrHauptMp40",
"U_LIB_GER_OfficerArzt_HeerPzrLhrLtMp40",
"U_LIB_GER_Officer_HeerPzrLhrLtMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrOfwMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrOfw12Mp40",
"U_LIB_GER_unterofficer_HeerPzrLhrOfw2Mp40",
"U_LIB_GER_smgunner_HeerPzrLhrOgefrMp40",
"U_LIB_GER_smgunner_HeerPzrLhrOgefr2Mp40",
"U_LIB_GER_Officer_HeerPzrLhrOltMp40",
"U_LIB_GER_ober_rifleman_HeerPzrLhrOschG43",
"U_LIB_GER_ober_rifleman_HeerPzrLhrOsch2G43",
"U_LIB_GER_Officer_HeerPzrLhrObstMp40",
"U_LIB_GER_medic_HeerPzrLhrK98",
"U_LIB_GER_medic_HeerPzrLhr12K98",
"U_LIB_GER_rifleman_HeerPzrLhrSchK98",
"U_LIB_GER_rifleman_HeerPzrLhrSch12K98",
"U_LIB_GER_rifleman_HeerPzrLhrSch13K98",
"U_LIB_GER_rifleman_HeerPzrLhrSch2K98",
"U_LIB_GER_unterofficer_HeerPzrLhrStfwMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrStfw12Mp40",
"U_LIB_GER_smgunner_HeerPzrLhrStgefrMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrUfwMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrUfw12Mp40",
"U_LIB_GER_unterofficer_HeerPzrLhrUfw2Mp40",
"U_LIB_GER_unterofficer_HeerPzrLhrUffzMp40",
"U_LIB_GER_unterofficer_HeerPzrLhrUffz12Mp40",
"U_LIB_GER_PzrGr_Crew_Unterofficer_HeerPzrLhrFwMp40",
"U_LIB_GER_PzrGr_Crew_Private_HeerPzrLhrGefrMp40",
"U_LIB_GER_PzrGr_Crew_Private_HeerPzrLhrGefr6yMp40",
"U_LIB_GER_PzrGr_Crew_Officer_HeerPzrLhrHptmMp40",
"U_LIB_GER_PzrGr_Crew_OfficerArzt_HeerPzrLhrLtMp40",
"U_LIB_GER_PzrGr_Crew_Officer_HeerPzrLhrLtMp40",
"U_LIB_GER_PzrGr_Crew_Unterofficer_HeerPzrLhrOfwMp40",
"U_LIB_GER_PzrGr_Crew_Private_HeerPzrLhrOgefrMp40",
"U_LIB_GER_PzrGr_Crew_Officer_HeerPzrLhrOltMp40",
"U_LIB_GER_PzrGr_Crew_Private_HeerPzrLhrOschG43",
"U_LIB_GER_Hauptmann",
"U_LIB_GER_PzrGr_medic_HeerPzrLhrSchK98",
"U_LIB_GER_PzrGr_Crew_Private_HeerPzrLhrSchK98",
"U_LIB_GER_PzrGr_Crew_Unterofficer_HeerPzrLhrStfwMp40",
"U_LIB_GER_PzrGr_Crew_Private_HeerPzrLhrStgefrMp40",
"U_LIB_GER_PzrGr_Crew_Unterofficer_HeerPzrLhrUfwMp40",
"U_LIB_GER_PzrGr_medic_HeerPzrLhrUffzK98",
"U_LIB_GER_PzrGr_Crew_Unterofficer_HeerPzrLhrUffzMp40",
"U_LIB_GER_unterofficer_HeerPzrLhr00v142pFw12Mp40",
"U_LIB_GER_rifleman_HeerPzrLhr00v142pSch12K98",
"U_LIB_GER_rifleman_HeerPzrLhr00v142pSch13K98",
"U_LIB_GER_unterofficer_HeerPzrLhr00v142pUfw13Mp40",
"U_LIB_GER_unterofficer_HeerPzrLhr00v143pFw13Mp40",
"U_LIB_GER_rifleman_HeerPzrLhr00v143pSch12K98",
"U_LIB_GER_rifleman_HeerPzrLhr00v143pSch13K98",
"U_LIB_GER_unterofficer_HeerPzrLhr00v143pUffz12Mp40",
"U_LIB_GER_rifleman_HeerPzrLhr00v144pSch12K98",
"U_LIB_GER_rifleman_HeerPzrLhr00v144pSch13K98",
"U_LIB_GER_unterofficer_HeerPzrLhr00v144pUfw12Mp40",
"U_LIB_GER_unterofficer_HeerPzrLhr00v144pUfw12Mp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerPzrLhr0sv0spbcFwMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerPzrLhr0sv0spbcGefrMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerPzrLhr0sv0spbcGefr6yMp40",
"U_LIB_GER_Sturm_Crew_Officer_HeerPzrLhr0sv0spbcHptmMp40",
"U_LIB_GER_Sturm_Crew_Officer_HeerPzrLhr0sv0spbcLtMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerPzrLhr0sv0spbcOfwMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerPzrLhr0sv0spbcOgefrMp40",
"U_LIB_GER_Sturm_Crew_Officer_HeerPzrLhr0sv0spbcOltMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerPzrLhr0sv0spbcOschMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerPzrLhr0sv0spbcSchMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerPzrLhr0sv0spbcStfwMp40",
"U_LIB_GER_Sturm_Crew_Private_HeerPzrLhr0sv0spbcStgefrMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerPzrLhr0sv0spbcUfwMp40",
"U_LIB_GER_Sturm_Crew_Unterofficer_HeerPzrLhr0sv0spbcUffzMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpgcFwMp40",
"U_LIB_GER_Tank_Crew_Private_HeerPzrLhr0tv0tpgcGefrMp40",
"U_LIB_GER_Tank_Crew_Private_HeerPzrLhr0tv0tpgcGefr6yMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerPzrLhr0tv0tpgcHptmMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerPzrLhr0tv0tpgcLtMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpgcOfwMp40",
"U_LIB_GER_Tank_Crew_Private_HeerPzrLhr0tv0tpgcOgefrMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerPzrLhr0tv0tpgcOltMp40",
"U_LIB_GER_Tank_Crew_Private_HeerPzrLhr0tv0tpgcOschMp40",
"U_LIB_GER_Tank_Crew_Private_HeerPzrLhr0tv0tpgcSchMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpgcStfwMp40",
"U_LIB_GER_Tank_Crew_Private_HeerPzrLhr0tv0tpgcStgefrMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpgcUfwMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpgcUffzMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpncFwMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerPzrLhr0tv0tpncHptmMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerPzrLhr0tv0tpncLtMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpncOfwMp40",
"U_LIB_GER_Tank_Crew_Officer_HeerPzrLhr0tv0tpncOltMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_HeerPzrLhr0tv0tpncStfwMp40",
"U_LIB_GER_Subofficer_camo_00v00pFwMp40",
"U_LIB_GER_Subofficer_camo_00v00pFw2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pFw3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pFw5Mp40",
"U_LIB_GER_Soldier_camo_00v00pGefrMp40",
"U_LIB_GER_Soldier_camo_00v00pGefr2Mp40",
"U_LIB_GER_Soldier_camo_00v00pGefr3Mp40",
"U_LIB_GER_Soldier_camo_00v00pGefr5Mp40",
"U_LIB_GER_Soldier_camo_00v00pGefr6yMp40",
"U_LIB_GER_Soldier_camo_00v00pGefr6y2Mp40",
"U_LIB_GER_Soldier_camo_00v00pGefr6y3Mp40",
"U_LIB_GER_Soldier_camo_00v00pGefr6y5Mp40",
"U_LIB_GER_Officer_camo_00v00pHptmMp40",
"U_LIB_GER_Officer_camo_00v00pLtMp40",
"U_LIB_GER_Subofficer_camo_00v00pOfwMp40",
"U_LIB_GER_Subofficer_camo_00v00pOfw2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pOfw3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pOfw5Mp40",
"U_LIB_GER_Soldier_camo_00v00pOgefrMp40",
"U_LIB_GER_Soldier_camo_00v00pOgefr2Mp40",
"U_LIB_GER_Soldier_camo_00v00pOgefr3Mp40",
"U_LIB_GER_Soldier_camo_00v00pOgefr5Mp40",
"U_LIB_GER_Officer_camo_00v00pOltMp40",
"U_LIB_GER_Soldier_camo_00v00pOschG43",
"U_LIB_GER_Soldier_camo_00v00pOsch2G43",
"U_LIB_GER_Soldier_camo_00v00pOsch3G43",
"U_LIB_GER_Soldier_camo_00v00pOsch5G43",
"U_LIB_GER_Soldier_camo_00v00pSantK98",
"U_LIB_GER_Soldier_camo_00v00pSchK98",
"U_LIB_GER_Soldier_camo_00v00pSch2K98",
"U_LIB_GER_Soldier_camo_00v00pSch3K98",
"U_LIB_GER_Soldier_camo_00v00pSch5K98",
"U_LIB_GER_Subofficer_camo_00v00pStfwMp40",
"U_LIB_GER_Subofficer_camo_00v00pStfw2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pStfw3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pStfw5Mp40",
"U_LIB_GER_Soldier_camo_00v00pStgefrMp40",
"U_LIB_GER_Soldier_camo_00v00pStgefr2Mp40",
"U_LIB_GER_Soldier_camo_00v00pStgefr3Mp40",
"U_LIB_GER_Soldier_camo_00v00pStgefr5Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUfwMp40",
"U_LIB_GER_Subofficer_camo_00v00pUfw2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUfw3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUfw5Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUffzMp40",
"U_LIB_GER_Subofficer_camo_00v00pUffz2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUffz3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUffz5Mp40",
"U_LIB_GER_scout_sniper_00v00pUffzK98zf39",
"U_LIB_GER_Subofficer_camo_122v00pFwMp40",
"U_LIB_GER_Subofficer_camo_122v00pFw2Mp40",
"U_LIB_GER_Subofficer_camo_122v00pFw3Mp40",
"U_LIB_GER_Subofficer_camo_122v00pFw5Mp40",
"U_LIB_GER_Soldier_camo_122v00pGefrMp40",
"U_LIB_GER_Soldier_camo_122v00pGefr2Mp40",
"U_LIB_GER_Soldier_camo_122v00pGefr3Mp40",
"U_LIB_GER_Soldier_camo_122v00pGefr5Mp40",
"U_LIB_GER_Soldier_camo_122v00pGefr6yMp40",
"U_LIB_GER_Soldier_camo_122v00pGefr6y2Mp40",
"U_LIB_GER_Soldier_camo_122v00pGefr6y3Mp40",
"U_LIB_GER_Soldier_camo_122v00pGefr6y5Mp40",
"U_LIB_GER_Officer_camo_122v00pHptmMp40",
"U_LIB_GER_Officer_camo_122v00pLtMp40",
"U_LIB_GER_Subofficer_camo_122v00pOfwMp40",
"U_LIB_GER_Subofficer_camo_122v00pOfw2Mp40",
"U_LIB_GER_Subofficer_camo_122v00pOfw3Mp40",
"U_LIB_GER_Subofficer_camo_122v00pOfw5Mp40",
"U_LIB_GER_Soldier_camo_122v00pOgefrMp40",
"U_LIB_GER_Soldier_camo_122v00pOgefr2Mp40",
"U_LIB_GER_Soldier_camo_122v00pOgefr3Mp40",
"U_LIB_GER_Soldier_camo_122v00pOgefr5Mp40",
"U_LIB_GER_Officer_camo_122v00pOltMp40",
"U_LIB_GER_Soldier_camo_122v00pOschG43",
"U_LIB_GER_Soldier_camo_122v00pOsch2G43",
"U_LIB_GER_Soldier_camo_122v00pOsch3G43",
"U_LIB_GER_Soldier_camo_122v00pOsch5G43",
"U_LIB_GER_Soldier_camo_122v00pSantK98",
"U_LIB_GER_Soldier_camo_122v00pSchK98",
"U_LIB_GER_Soldier_camo_122v00pSch2K98",
"U_LIB_GER_Soldier_camo_122v00pSch3K98",
"U_LIB_GER_Soldier_camo_122v00pSch5K98",
"U_LIB_GER_Subofficer_camo_122v00pStfwMp40",
"U_LIB_GER_Subofficer_camo_122v00pStfw2Mp40",
"U_LIB_GER_Subofficer_camo_122v00pStfw3Mp40",
"U_LIB_GER_Subofficer_camo_122v00pStfw5Mp40",
"U_LIB_GER_Soldier_camo_122v00pStgefrMp40",
"U_LIB_GER_Soldier_camo_122v00pStgefr2Mp40",
"U_LIB_GER_Soldier_camo_122v00pStgefr3Mp40",
"U_LIB_GER_Soldier_camo_122v00pStgefr5Mp40",
"U_LIB_GER_Subofficer_camo_122v00pUfwMp40",
"U_LIB_GER_Subofficer_camo_122v00pUfw2Mp40",
"U_LIB_GER_Subofficer_camo_122v00pUfw3Mp40",
"U_LIB_GER_Subofficer_camo_122v00pUfw5Mp40",
"U_LIB_GER_Subofficer_camo_122v00pUffzMp40",
"U_LIB_GER_Officer_Heer122v00pLtMp40",
"U_LIB_GER_Officer_Heer122v00pOltMp40",
"U_LIB_GER_rifleman_KazakiKzk11K98",
"U_LIB_GER_rifleman_KazakiKzk21K98",
"U_LIB_GER_Officer_KazakiKrzMp40",
"U_LIB_GER_Officer_KazakiPdslMp40",
"U_LIB_GER_smgunner_KazakiPkzn11Mp40",
"U_LIB_GER_smgunner_KazakiPkzn21Mp40",
"U_LIB_GER_medic_Kazaki11K98",
"U_LIB_GER_medicB_Kazaki11K98",
"U_LIB_GER_Officer_KazakiStnMp40",
"U_LIB_GER_unterofficer_KazakiUrdk11Mp40",
"U_LIB_GER_unterofficer_KazakiUrdk21Mp40",
"U_LIB_GER_unterofficer_KazakiVkmt11Mp40",
"U_LIB_GER_unterofficer_KazakiVkmt21Mp40",
"U_LIB_GER_rifleman_KazakiKonKzkK98",
"U_LIB_GER_Officer_KazakiKonKrzSvt40",
"U_LIB_GER_Officer_KazakiKonPpkkM1908",
"U_LIB_GER_Officer_KazakiKonPdslMp40",
"U_LIB_GER_Officer_KazakiKonPkkM1908",
"U_LIB_GER_rifleman_KazakiKonPkznK98",
"U_LIB_GER_Officer_KazakiKonStnkMp40",
"U_LIB_GER_rifleman_KazakiKonUrdkPpsch41d",
"U_LIB_GER_rifleman_KazakiKonVkmtMp40",
"U_LIB_GER_Officer_KazakiKonYslMp40",
"U_LIB_GER_unterofficer_LuftFwMp40",
"U_LIB_GER_rifleman_LuftSchK98",
"U_LIB_GER_smgunner_LuftGefrMp40",
"U_LIB_GER_smgunner_LuftGefr6yMp40",
"U_LIB_GER_Officer_LuftHptmMp40",
"U_LIB_GER_Officer_LuftLtMp40",
"U_LIB_GER_unterofficer_LuftOfwMp40",
"U_LIB_GER_ober_rifleman_LuftOschG43",
"U_LIB_GER_smgunner_LuftOgefrMp40",
"U_LIB_GER_Officer_LuftOltMp40",
"U_LIB_GER_medic_LuftK98",
"U_LIB_GER_unterofficer_LuftStfwMp40",
"U_LIB_GER_smgunner_LuftStgefrMp40",
"U_LIB_GER_unterofficer_LuftUfwMp40",
"U_LIB_GER_unterofficer_LuftUffzMp40",
"U_LIB_GER_unterofficer_LuftbcvbtpFwMp40",
"U_LIB_GER_rifleman_LuftbcvbtpSch3K98",
"U_LIB_GER_smgunner_LuftbcvbtpGefrMp40",
"U_LIB_GER_smgunner_LuftbcvbtpGefr6yG43",
"U_LIB_GER_OfficerArzt_LuftbcvbtpLtMp40",
"U_LIB_GER_unterofficer_LuftbcvbtpOfwMp40",
"U_LIB_GER_ober_rifleman_LuftbcvbtpOschG43",
"U_LIB_GER_smgunner_LuftbcvbtpOgefrStg44",
"U_LIB_GER_Officer_LuftbcvbtpOltMp40",
"U_LIB_GER_medic_LuftbcvbtpK98",
"U_LIB_GER_smgunner_LuftbcvbtpStgefrMp40",
"U_LIB_GER_unterofficer_LuftbcvbtpUffzMp40",
"U_LIB_GER_unterofficer_LuftbfvbcpFwMp40",
"U_LIB_GER_rifleman_LuftbfvbcpSch3K98",
"U_LIB_GER_smgunner_LuftbfvbcpGefrG43",
"U_LIB_GER_smgunner_LuftbfvbcpGefr6yMp40",
"U_LIB_GER_ober_rifleman_LuftbfvbcpOschG43",
"U_LIB_GER_smgunner_LuftbfvbcpOgefrG43",
"U_LIB_GER_Officer_LuftbfvbcpOltMp40",
"U_LIB_GER_medic_LuftbfvbcpK98",
"U_LIB_GER_unterofficer_LuftbfvbcpStfwMp40",
"U_LIB_GER_smgunner_LuftbfvbcpStgefrMp40",
"U_LIB_GER_unterofficer_LuftbfvbcpUfwMp40",
"U_LIB_GER_Officer_LuftbfvbfpHptmMp40",
"U_LIB_GER_rifleman_LuftbfvgfpSchK98",
"U_LIB_GER_smgunner_LuftbfvgfpGefrMp40",
"U_LIB_GER_smgunner_LuftbfvgfpGefr6yG43",
"U_LIB_GER_Officer_LuftbfvgfpLtMp40",
"U_LIB_GER_unterofficer_LuftbfvgfpOfwMp40",
"U_LIB_GER_ober_rifleman_LuftbfvgfpOschG43",
"U_LIB_GER_smgunner_LuftbfvgfpOgefrMp40",
"U_LIB_GER_medic_LuftbfvgfpK98",
"U_LIB_GER_smgunner_LuftbfvgfpStgefrStg44",
"U_LIB_GER_unterofficer_LuftbfvgfpUfwStg44",
"U_LIB_GER_unterofficer_LuftbfvgfpUffzMp40",
"U_LIB_GER_pilot_LuftHptmM1908",
"U_LIB_GER_pilot_LuftLtM1908",
"U_LIB_GER_pilot_LuftOltM1908",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0spbcFwMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0spbcGefrMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0spbcGefr6yMp40",
"U_LIB_GER_Tank_Crew_Officer_Heer0tv0spbcHptmMp40",
"U_LIB_GER_Tank_Crew_Officer_Heer0tv0spbcLtMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0spbcOfwMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0spbcOgefrMp40",
"U_LIB_GER_Tank_Crew_Officer_Heer0tv0spbcOltMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0spbcOschMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0spbcSchMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0spbcStfwMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0spbcStgefrMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0spbcUfwMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0spbcUffzMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0tpgcFwMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0tpgcGefrMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0tpgcGefr6yMp40",
"U_LIB_GER_Tank_Crew_Officer_Heer0tv0tpgcHptmMp40",
"U_LIB_GER_Tank_Crew_Officer_Heer0tv0tpgcLtMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0tpgcOfwMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0tpgcOgefrMp40",
"U_LIB_GER_Tank_Crew_Officer_Heer0tv0tpgcOltMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0tpgcOschMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0tpgcSchMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0tpgcStfwMp40",
"U_LIB_GER_Tank_Crew_Private_Heer0tv0tpgcStgefrMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0tpgcUfwMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_Heer0tv0tpgcUffzMp40",
"U_LIB_GER_unterofficer_ROAFdfbMp40",
"U_LIB_GER_unterofficer_ROAFdfb2Mp40",
"U_LIB_GER_Officer_ROAKptMp40",
"U_LIB_GER_Officer_ROAMyrMp40",
"U_LIB_GER_Officer_ROAPpkkMp40",
"U_LIB_GER_OfficerArzt_ROAPpckMp40",
"U_LIB_GER_OfficerArztB_ROAPpckMp40",
"U_LIB_GER_Officer_ROAPpckMp40",
"U_LIB_GER_Officer_ROAPkkMp40",
"U_LIB_GER_Officer_ROAPckMp40",
"U_LIB_GER_rifleman_ROARdvK98",
"U_LIB_GER_rifleman_ROARdv2K98",
"U_LIB_GER_medic_ROAK98",
"U_LIB_GER_medicB_ROAK98",
"U_LIB_GER_unterofficer_ROAUoftMp40",
"U_LIB_GER_unterofficer_ROAUoft2Mp40",
"U_LIB_GER_smgunner_ROAYftrMp40",
"U_LIB_GER_smgunner_ROAYftr2Mp40",
"U_LIB_GER_Soldier_camo_142v00pMnnK98",
"U_LIB_GER_Soldier_camo_142v00pOmnnG43",
"U_LIB_GER_Subofficer_camo_142v00pOschaMp40",
"U_LIB_GER_Officer_camo_142v00pOstufMp40",
"U_LIB_GER_Sanitater_camo_142v00pRttfK98",
"U_LIB_GER_Soldier_camo_142v00pStrmmMp40",
"U_LIB_GER_Subofficer_camo_142v00pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_142v00pUschaMp40",
"U_LIB_GER_Subofficer_camo_143v00pHschaMp40",
"U_LIB_GER_Officer_camo_143v00pHstufMp40",
"U_LIB_GER_Sanitater_camo_143v00pMnnK98",
"U_LIB_GER_Soldier_camo_143v00pMnnK98",
"U_LIB_GER_Soldier_camo_143v00pOmnnG43",
"U_LIB_GER_Soldier_camo_143v00pRttfMp40",
"U_LIB_GER_Subofficer_camo_143v00pScharfMp40",
"U_LIB_GER_Soldier_camo_143v00pStrmmMp40",
"U_LIB_GER_Officer_camo_143v00pUstufMp40",
"U_LIB_GER_Officer_SSHstufabMP40",
"U_LIB_GER_Officer_SSOstufabMP40",
"U_LIB_GER_Officer_SSStubafabM1908",
"U_LIB_GER_Officer_SSUstufabMP40",
"U_LIB_GER_Unterofficer_SSHschaMP40",
"U_LIB_GER_Officer_SSHstufsbMP40",
"U_LIB_GER_Officer_SSHstufsbMP40",
"U_LIB_GER_Rifleman_SSOmnnG43",
"U_LIB_GER_Unterofficer_SSOschaMP40",
"U_LIB_GER_Officer_SSOstufsbMP40",
"U_LIB_GER_Unterofficer_SSRttfMP40",
"U_LIB_GER_Unterofficer_SSScharfMP40",
"U_LIB_GER_Officer_SSStubafsbM1908",
"U_LIB_GER_Unterofficer_SSStrmmMP40",
"U_LIB_GER_Unterofficer_SSStuscharfMP40",
"U_LIB_GER_Unterofficer_SSUschaMP40",
"U_LIB_GER_Officer_SSUstufsbMP40",
"U_LIB_GER_rifleman_WssFrsbrg00v03pMnn12K98",
"U_LIB_GER_unterofficer_WssFrsbrg00v03pUscha12Mp40",
"U_LIB_GER_rifleman_WssFrsbrg00v09pMnn12K98",
"U_LIB_GER_unterofficer_WssFrsbrgHschaMp40",
"U_LIB_GER_unterofficer_WssFrsbrgHscha12Mp40",
"U_LIB_GER_Officer_WssFrsbrgHstufMp40",
"U_LIB_GER_medic_WssFrsbrgK98",
"U_LIB_GER_rifleman_WssFrsbrgMnnK98",
"U_LIB_GER_medic_WssFrsbrg12K98",
"U_LIB_GER_rifleman_WssFrsbrgMnn12K98",
"U_LIB_GER_ober_rifleman_WssFrsbrgOmnnG43",
"U_LIB_GER_unterofficer_WssFrsbrgOschaMp40",
"U_LIB_GER_unterofficer_WssFrsbrgOscha12Mp40",
"U_LIB_GER_Officer_WssFrsbrgOstufMp40",
"U_LIB_GER_smgunner_WssFrsbrgRttfMp40",
"U_LIB_GER_unterofficer_WssFrsbrg00v03pScharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrgScharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrgScharf12Mp40",
"U_LIB_GER_Officer_WssFrsbrgStubafMp40",
"U_LIB_GER_medic_WssFrsbrgStrmmK98",
"U_LIB_GER_smgunner_WssFrsbrgStrmmMp40",
"U_LIB_GER_unterofficer_WssFrsbrgStuscharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrgStuscharf12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgUschaMp40",
"U_LIB_GER_unterofficer_WssFrsbrgUscha12Mp40",
"U_LIB_GER_Officer_WssFrsbrgUstufMp40",
"U_LIB_GER_rifleman_WssFrsbrg00v27pMnn12K98",
"U_LIB_GER_rifleman_WssFrsbrg00v41pMnn12K98",
"U_LIB_GER_Officer_WssFrsbrg03v00pOstufMp40",
"U_LIB_GER_Officer_WssFrsbrg03v00pUstufMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpbcMnnMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpbcOmnnMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpbcOschaMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpbcStrmmMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpbcUschaMp40",
"U_LIB_GER_Tank_Crew_Officer_WssFrsbrg0tv0tpbcUstufMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpgcHschaMp40",
"U_LIB_GER_Tank_Crew_Officer_WssFrsbrg0tv0tpgcOstufMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpgcRttfMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpgcScharfMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpgcStuscharfMp40",
"U_LIB_GER_Tank_Crew_Officer_WssFrsbrg0tv0tpncHstufMp40",
"U_LIB_GER_Subofficer_camo_00v00pHschaMp40",
"U_LIB_GER_Subofficer_camo_00v00pHscha2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pHscha3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pHscha5Mp40",
"U_LIB_GER_Officer_camo_00v00pHstufMp40",
"U_LIB_GER_Soldier_camo_00v00pMnnK98",
"U_LIB_GER_Soldier_camo_00v00pMnn2K98",
"U_LIB_GER_Soldier_camo_00v00pMnn3K98",
"U_LIB_GER_Soldier_camo_00v00pMnn5K98",
"U_LIB_GER_Soldier_camo_00v00pOmnnG43",
"U_LIB_GER_Soldier_camo_00v00pOmnn2G43",
"U_LIB_GER_Soldier_camo_00v00pOmnn3G43",
"U_LIB_GER_Soldier_camo_00v00pOmnn5G43",
"U_LIB_GER_Subofficer_camo_00v00pOschaMp40",
"U_LIB_GER_Subofficer_camo_00v00pOscha2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pOscha3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pOscha5Mp40",
"U_LIB_GER_Officer_camo_00v00pOstufMp40",
"U_LIB_GER_Soldier_camo_00v00pRttfMp40",
"U_LIB_GER_Soldier_camo_00v00pRttf2Mp40",
"U_LIB_GER_Soldier_camo_00v00pRttf3Mp40",
"U_LIB_GER_Soldier_camo_00v00pRttf5Mp40",
"U_LIB_GER_Soldier_camo_00v00pSantwssK98",
"U_LIB_GER_Subofficer_camo_00v00pScharfMp40",
"U_LIB_GER_Subofficer_camo_00v00pScharf2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pScharf3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pScharf5Mp40",
"U_LIB_GER_Officer_camo_00v00pStubafMp40",
"U_LIB_GER_Soldier_camo_00v00pStrmmMp40",
"U_LIB_GER_Soldier_camo_00v00pStrmm2Mp40",
"U_LIB_GER_Soldier_camo_00v00pStrmm3Mp40",
"U_LIB_GER_Soldier_camo_00v00pStrmm5Mp40",
"U_LIB_GER_Subofficer_camo_00v00pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_00v00pStuscharf2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pStuscharf3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pStuscharf5Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUschaMp40",
"U_LIB_GER_Subofficer_camo_00v00pUscha2Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUscha3Mp40",
"U_LIB_GER_Subofficer_camo_00v00pUscha5Mp40",
"U_LIB_GER_Officer_camo_00v00pUstufMp40",
"U_LIB_GER_Subofficer_camo_27v09pHschaMp40",
"U_LIB_GER_Soldier_camo_27v09pMnnK98",
"U_LIB_GER_Soldier_camo_27v09pOmnnG43",
"U_LIB_GER_Subofficer_camo_27v09pOschaMp40",
"U_LIB_GER_Officer_camo_27v09pOstufMp40",
"U_LIB_GER_Soldier_camo_27v09pRttfMp40",
"U_LIB_GER_Subofficer_camo_27v09pScharfMp40",
"U_LIB_GER_Soldier_camo_27v09pStrmmMp40",
"U_LIB_GER_Subofficer_camo_27v09pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_27v09pUschaMp40",
"U_LIB_GER_Officer_camo_27v09pUstufMp40",
"U_LIB_GER_Subofficer_camo_27v00pHschaMp40",
"U_LIB_GER_Subofficer_camo_27v00pHscha2Mp40",
"U_LIB_GER_Subofficer_camo_27v00pHscha3Mp40",
"U_LIB_GER_Subofficer_camo_27v00pHscha5Mp40",
"U_LIB_GER_Officer_camo_27v00pHstufMp40",
"U_LIB_GER_Soldier_camo_27v00pMnnK98",
"U_LIB_GER_Subofficer_camo_27v00pScharfMp40",
"U_LIB_GER_Subofficer_camo_27v00pScharf2Mp40",
"U_LIB_GER_Subofficer_camo_27v00pScharf3Mp40",
"U_LIB_GER_Subofficer_camo_27v00pScharf5Mp40",
"U_LIB_GER_Officer_camo_27v00pStubafMp40",
"U_LIB_GER_Soldier_camo_27v00pStrmmMp40",
"U_LIB_GER_Soldier_camo_27v00pStrmm2Mp40",
"U_LIB_GER_Soldier_camo_27v00pStrmm3Mp40",
"U_LIB_GER_Soldier_camo_27v00pStrmm5Mp40",
"U_LIB_GER_Subofficer_camo_27v00pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_27v00pStuscharf2Mp40",
"U_LIB_GER_Subofficer_camo_27v00pStuscharf3Mp40",
"U_LIB_GER_Subofficer_camo_27v00pStuscharf5Mp40",
"U_LIB_GER_Subofficer_camo_27v00pUschaMp40",
"U_LIB_GER_Subofficer_camo_27v00pUscha2Mp40",
"U_LIB_GER_Subofficer_camo_27v00pUscha3Mp40",
"U_LIB_GER_Subofficer_camo_27v00pUscha5Mp40",
"U_LIB_GER_Officer_camo_27v00pUstufMp40",
"U_LIB_GER_Subofficer_camo_27v27pHschaMp40",
"U_LIB_GER_scout_sniper_27v27pHschaMp40",
"U_LIB_GER_Officer_camo_27v27pHstufMp40",
"U_LIB_GER_Soldier_camo_27v27pMnnK98",
"U_LIB_GER_Soldier_camo_27v27pSantwssK98",
"U_LIB_GER_scout_sniper_27v27pMnnK98",
"U_LIB_GER_scout_sniper_27v27pSantwssK98",
"U_LIB_GER_Soldier_camo_27v27pOmnnG43",
"U_LIB_GER_scout_sniper_27v27pOmnnG43",
"U_LIB_GER_Subofficer_camo_27v27pOschaMp40",
"U_LIB_GER_scout_sniper_27v27pOschaMp40",
"U_LIB_GER_Officer_camo_27v27pOstufMp40",
"U_LIB_GER_Soldier_camo_27v27pRttfMp40",
"U_LIB_GER_scout_sniper_27v27pRttfMp40",
"U_LIB_GER_Subofficer_camo_27v27pScharfMp40",
"U_LIB_GER_scout_sniper_27v27pScharfMp40",
"U_LIB_GER_Officer_camo_27v27pStubafMp40",
"U_LIB_GER_Soldier_camo_27v27pStrmmMp40",
"U_LIB_GER_scout_sniper_27v27pStrmmMp40",
"U_LIB_GER_Subofficer_camo_27v27pStuscharfMp40",
"U_LIB_GER_scout_sniper_27v27pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_27v27pUschaMp40",
"U_LIB_GER_scout_sniper_27v27pUschaMp40",
"U_LIB_GER_Officer_camo_27v27pUstufMp40",
"U_LIB_GER_Subofficer_camo_03v00pHschaMp40",
"U_LIB_GER_Subofficer_camo_03v00pHscha2Mp40",
"U_LIB_GER_Subofficer_camo_03v00pHscha3Mp40",
"U_LIB_GER_Subofficer_camo_03v00pHscha5Mp40",
"U_LIB_GER_Officer_camo_03v00pHstufMp40",
"U_LIB_GER_Soldier_camo_03v00pMnnK98",
"U_LIB_GER_Soldier_camo_03v00pSantwssK98",
"U_LIB_GER_Soldier_camo_03v00pMnn2K98",
"U_LIB_GER_Soldier_camo_03v00pSantwss2K98",
"U_LIB_GER_Soldier_camo_03v00pMnn3K98",
"U_LIB_GER_Soldier_camo_03v00pSantwss3K98",
"U_LIB_GER_Soldier_camo_03v00pMnn5K98",
"U_LIB_GER_Soldier_camo_03v00pSantwss5K98",
"U_LIB_GER_Soldier_camo_03v00pOmnnG43",
"U_LIB_GER_Soldier_camo_03v00pOmnn2G43",
"U_LIB_GER_Soldier_camo_03v00pOmnn3G43",
"U_LIB_GER_Soldier_camo_03v00pOmnn5G43",
"U_LIB_GER_Subofficer_camo_03v00pOschaMp40",
"U_LIB_GER_Subofficer_camo_03v00pOscha2Mp40",
"U_LIB_GER_Subofficer_camo_03v00pOscha3Mp40",
"U_LIB_GER_Subofficer_camo_03v00pOscha5Mp40",
"U_LIB_GER_Officer_camo_03v00pOstufMp40",
"U_LIB_GER_Soldier_camo_03v00pRttfMp40",
"U_LIB_GER_Soldier_camo_03v00pRttf2Mp40",
"U_LIB_GER_Soldier_camo_03v00pRttf3Mp40",
"U_LIB_GER_Soldier_camo_03v00pRttf5Mp40",
"U_LIB_GER_Subofficer_camo_03v00pScharfMp40",
"U_LIB_GER_Subofficer_camo_03v00pScharf2Mp40",
"U_LIB_GER_Subofficer_camo_03v00pScharf3Mp40",
"U_LIB_GER_Subofficer_camo_03v00pScharf5Mp40",
"U_LIB_GER_Officer_camo_03v00pStubafMp40",
"U_LIB_GER_Soldier_camo_03v00pStrmmMp40",
"U_LIB_GER_Soldier_camo_03v00pSantStrmmG43",
"U_LIB_GER_Soldier_camo_03v00pStrmm2Mp40",
"U_LIB_GER_Soldier_camo_03v00pSantStrmm2G43",
"U_LIB_GER_Soldier_camo_03v00pStrmm3Mp40",
"U_LIB_GER_Soldier_camo_03v00pSantStrmm3G43",
"U_LIB_GER_Soldier_camo_03v00pStrmm5Mp40",
"U_LIB_GER_Soldier_camo_03v00pSantStrmm5G43",
"U_LIB_GER_Subofficer_camo_03v00pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_03v00pStuscharf2Mp40",
"U_LIB_GER_Subofficer_camo_03v00pStuscharf3Mp40",
"U_LIB_GER_Subofficer_camo_03v00pStuscharf5Mp40",
"U_LIB_GER_Subofficer_camo_03v00pUschaMp40",
"U_LIB_GER_Subofficer_camo_03v00pUscha2Mp40",
"U_LIB_GER_Subofficer_camo_03v00pUscha3Mp40",
"U_LIB_GER_Subofficer_camo_03v00pUscha5Mp40",
"U_LIB_GER_Officer_camo_03v00pUstufMp40",
"U_LIB_GER_Subofficer_camo_41v00pHschaMp40",
"U_LIB_GER_Subofficer_camo_41v00pHscha2Mp40",
"U_LIB_GER_Subofficer_camo_41v00pHscha3Mp40",
"U_LIB_GER_Subofficer_camo_41v00pHscha5Mp40",
"U_LIB_GER_Officer_camo_41v00pHstufMp40",
"U_LIB_GER_Soldier_camo_41v00pSantwssK98",
"U_LIB_GER_Soldier_camo_41v00pMnnK98",
"U_LIB_GER_Soldier_camo_41v00pSantwss2K98",
"U_LIB_GER_Soldier_camo_41v00pMnn2K98",
"U_LIB_GER_Soldier_camo_41v00pSantwss3K98",
"U_LIB_GER_Soldier_camo_41v00pMnn3K98",
"U_LIB_GER_Soldier_camo_41v00pSantwss5K98",
"U_LIB_GER_Soldier_camo_41v00pOmnnG43",
"U_LIB_GER_Soldier_camo_41v00pOmnn2G43",
"U_LIB_GER_Soldier_camo_41v00pOmnn3G43",
"U_LIB_GER_Soldier_camo_41v00pOmnn5G43",
"U_LIB_GER_Subofficer_camo_41v00pOschaMp40",
"U_LIB_GER_Subofficer_camo_41v00pOscha2Mp40",
"U_LIB_GER_Subofficer_camo_41v00pOscha3Mp40",
"U_LIB_GER_Subofficer_camo_41v00pOscha5Mp40",
"U_LIB_GER_Officer_camo_41v00pOstufMp40",
"U_LIB_GER_Soldier_camo_41v00pRttfMp40",
"U_LIB_GER_Soldier_camo_41v00pRttf2Mp40",
"U_LIB_GER_Soldier_camo_41v00pRttf3Mp40",
"U_LIB_GER_Soldier_camo_41v00pRttf5Mp40",
"U_LIB_GER_Subofficer_camo_41v00pScharfMp40",
"U_LIB_GER_Subofficer_camo_41v00pScharf2Mp40",
"U_LIB_GER_Subofficer_camo_41v00pScharf3Mp40",
"U_LIB_GER_Subofficer_camo_41v00pScharf5Mp40",
"U_LIB_GER_Officer_camo_41v00pStubafMp40",
"U_LIB_GER_Soldier_camo_41v00pStrmmMp40",
"U_LIB_GER_Soldier_camo_41v00pStrmm2Mp40",
"U_LIB_GER_Soldier_camo_41v00pStrmm3Mp40",
"U_LIB_GER_Soldier_camo_41v00pStrmm5Mp40",
"U_LIB_GER_Subofficer_camo_41v00pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_41v00pStuscharf2Mp40",
"U_LIB_GER_Subofficer_camo_41v00pStuscharf3Mp40",
"U_LIB_GER_Subofficer_camo_41v00pStuscharf5Mp40",
"U_LIB_GER_Subofficer_camo_41v00pUschaMp40",
"U_LIB_GER_Subofficer_camo_41v00pUscha3Mp40",
"U_LIB_GER_Subofficer_camo_41v00pUscha5Mp40",
"U_LIB_GER_Officer_camo_41v00pUstufMp40",
"U_LIB_GER_Subofficer_camo_41v03pUschaMp40",
"U_LIB_GER_Subofficer_camo_41v41pHschaMp40",
"U_LIB_GER_scout_sniper_41v41pHschaMp40",
"U_LIB_GER_Officer_camo_41v41pHstufMp40",
"U_LIB_GER_scout_sniper_41v41pHstufMp40",
"U_LIB_GER_Soldier_camo_41v41pMnnK98",
"U_LIB_GER_scout_sniper_41v41pMnnK98",
"U_LIB_GER_Soldier_camo_41v41pOmnnG43",
"U_LIB_GER_scout_sniper_41v41pOmnnG43",
"U_LIB_GER_Subofficer_camo_41v41pOschaMp40",
"U_LIB_GER_scout_sniper_41v41pOschaMp40",
"U_LIB_GER_scout_sniper_41v41pOstufMp40",
"U_LIB_GER_Officer_camo_41v41pOstufMp40",
"U_LIB_GER_Soldier_camo_41v41pRttfMp40",
"U_LIB_GER_scout_sniper_41v41pRttfMp40",
"U_LIB_GER_Soldier_camo_41v41pSantwssK98",
"U_LIB_GER_Subofficer_camo_41v41pScharfMp40",
"U_LIB_GER_scout_sniper_41v41pScharfMp40",
"U_LIB_GER_Officer_camo_41v41pStubafMp40",
"U_LIB_GER_Soldier_camo_41v41pStrmmMp40",
"U_LIB_GER_scout_sniper_41v41pStrmmMp40",
"U_LIB_GER_Subofficer_camo_41v41pStuscharfMp40",
"U_LIB_GER_scout_sniper_41v41pStuscharfMp40",
"U_LIB_GER_Subofficer_camo_41v41pUschaMp40",
"U_LIB_GER_scout_sniper_41v41pUschaMp40",
"U_LIB_GER_Officer_camo_41v41pUstufMp40",
"U_LIB_GER_scout_sniper_41v41pUstufMp40",
"U_LIB_GER_unterofficer_WssHschaMp40",
"U_LIB_GER_unterofficer_WssHscha12Mp40",
"U_LIB_GER_unterofficer_WssHscha2Mp40",
"U_LIB_GER_Officer_WssHstufMp40",
"U_LIB_GER_medic_WssK98",
"U_LIB_GER_rifleman_WssMnnK98",
"U_LIB_GER_medic_Wss12K98",
"U_LIB_GER_rifleman_WssMnn12K98",
"U_LIB_GER_rifleman_WssMnn2K98",
"U_LIB_GER_ober_rifleman_WssOmnnG43",
"U_LIB_GER_ober_rifleman_WssOmnn2G43",
"U_LIB_GER_unterofficer_WssOschaMp40",
"U_LIB_GER_unterofficer_WssOscha12Mp40",
"U_LIB_GER_unterofficer_WssOscha2Mp40",
"U_LIB_GER_Officer_WssOstufMp40",
"U_LIB_GER_smgunner_WssRttfMp40",
"U_LIB_GER_smgunner_WssRttf2Mp40",
"U_LIB_GER_unterofficer_WssScharfMp40",
"U_LIB_GER_unterofficer_WssScharf12Mp40",
"U_LIB_GER_unterofficer_WssScharf2Mp40",
"U_LIB_GER_Officer_WssStubafMp40",
"U_LIB_GER_medic_WssStrmmK98",
"U_LIB_GER_smgunner_WssStrmmMp40",
"U_LIB_GER_smgunner_WssStrmm2Mp40",
"U_LIB_GER_unterofficer_WssStuscharfMp40",
"U_LIB_GER_unterofficer_WssStuscharf12Mp40",
"U_LIB_GER_unterofficer_WssStuscharf2Mp40",
"U_LIB_GER_unterofficer_WssUschaMp40",
"U_LIB_GER_unterofficer_WssUscha12Mp40",
"U_LIB_GER_unterofficer_WssUscha2Mp40",
"U_LIB_GER_Officer_WssUstufMp40",
"U_LIB_GER_unterofficer_Wss00v03pScharfMp40",
"U_LIB_GER_Officer_Wss27v00pOstufMp40",
"U_LIB_GER_Officer_Wss27v00pUstufMp40",
"U_LIB_GER_Officer_Wss03v00pOstufMp40",
"U_LIB_GER_Officer_Wss03v00pUstufMp40",

//Stuff I dunno
"H_LIB_GER_Cap_SS",
"H_LIB_GER_Cap_WSS",
"H_LIB_GER_Cap_WSS_Bm",
"H_LIB_GER_Cap_WSS00",
"H_LIB_GER_Cap_WSS03",
"H_LIB_GER_Cap_WSS03B",
"H_LIB_GER_Cap_WSS09",
"H_LIB_GER_Cap_WSS15",
"H_LIB_GER_Cap_WSS19",
"H_LIB_GER_Cap_WSS27",
"H_LIB_GER_Cap_WSS41",
"H_LIB_GER_CapOfficer_SS",
"H_LIB_GER_CapOfficer_WSS",
"H_LIB_GER_CapOfficer_WSS_Bo",
"H_LIB_GER_Helmet_WSS1024T1",
"H_LIB_GER_Helmet_WSS1024T2",
"H_LIB_GER_Helmet_WSS2048T1",
"H_LIB_GER_Helmet_WSS2048T2",
"H_LIB_GER_Helmet_WSS40961T1",
"H_LIB_GER_Helmet_WSS40961T2",
"H_LIB_GER_Helmet_WSS40962T1",
"H_LIB_GER_Helmet_WSS40962T2",
"H_LIB_GER_Helmet_WSS40963T1",
"H_LIB_GER_Helmet_WSS40963T2",
"H_LIB_GER_Helmet_WSSCP541T1",
"H_LIB_GER_Helmet_WSSCP541T2",
"H_LIB_GER_Helmet_WSSCP542T1",
"H_LIB_GER_Helmet_WSSCP542T2",
"H_LIB_GER_Helmet_WSSFSJ1024T1",
"H_LIB_GER_Helmet_WSSFSJ1024T2",
"H_LIB_GER_Helmet_WSSFSJ2048T1",
"H_LIB_GER_Helmet_WSSFSJ2048T2",
"H_LIB_GER_Helmet_WSSFSJ3T1",
"H_LIB_GER_Helmet_WSSFSJ3T2",
"H_LIB_GER_Helmet_WSSFSJ40961T1",
"H_LIB_GER_Helmet_WSSFSJ40961T2",
"H_LIB_GER_Helmet_WSSFSJ40962T1",
"H_LIB_GER_Helmet_WSSFSJ40962T2",
"H_LIB_GER_Helmet_WSSFSJ40963T1",
"H_LIB_GER_Helmet_WSSFSJ40963T2",
"H_LIB_GER_Helmet_WSSFSJ4T1",
"H_LIB_GER_Helmet_WSSFSJ4T2",
"H_LIB_GER_Helmet_WSSFSJ541T1",
"H_LIB_GER_Helmet_WSSFSJ541T2",
"H_LIB_GER_Helmet_WSSFSJ542T1",
"H_LIB_GER_Helmet_WSSFSJ542T2",
"H_LIB_GER_Helmet_WSSFSJgaT1",
"H_LIB_GER_Helmet_WSSFSJgaT2",
"H_LIB_GER_Helmet_WSSFSJgcT1",
"H_LIB_GER_Helmet_WSSFSJgcT2",
"H_LIB_GER_Helmet_WSSFSJgdT1",
"H_LIB_GER_Helmet_WSSFSJgdT2",
"H_LIB_GER_Helmet_WSSFSJPaintedT1",
"H_LIB_GER_Helmet_WSSFSJPaintedT2",
"H_LIB_GER_Helmet_WSSFSJW01T1",
"H_LIB_GER_Helmet_WSSFSJW01T2",
"H_LIB_GER_Helmet_WSSFSJW02T1",
"H_LIB_GER_Helmet_WSSFSJW02T2",
"H_LIB_GER_Helmet_WSSFSJW11T1",
"H_LIB_GER_Helmet_WSSFSJW11T2",
"H_LIB_GER_Helmet_WSSFSJW21T1",
"H_LIB_GER_Helmet_WSSFSJW21T2",
"H_LIB_GER_Helmet_WSSg",
"H_LIB_GER_Helmet_WSSgc",
"H_LIB_GER_Helmet_WSSgcT1",
"H_LIB_GER_Helmet_WSSgcT2",
"H_LIB_GER_Helmet_WSSgd",
"H_LIB_GER_Helmet_WSSgdT1",
"H_LIB_GER_Helmet_WSSgdT2",
"H_LIB_GER_Helmet_WSSgT1",
"H_LIB_GER_Helmet_WSSgT2",
"H_LIB_GER_Helmet_WSSW01T1",
"H_LIB_GER_Helmet_WSSW01T2",
"H_LIB_GER_Helmet_WSSW02T1",
"H_LIB_GER_Helmet_WSSW02T2",
"H_LIB_GER_Helmet_WSSW11T1",
"H_LIB_GER_Helmet_WSSW11T2",
"H_LIB_GER_Helmet_WSSW21T1",
"H_LIB_GER_Helmet_WSSW21T2",
"H_LIB_GER_Helmet_WSSW32T1",
"H_LIB_GER_Helmet_WSSW32T2",
"H_LIB_GER_Helmetnet_WSS1024T1",
"H_LIB_GER_Helmetnet_WSS1024T2",
"H_LIB_GER_Helmetnet_WSS2048T1",
"H_LIB_GER_Helmetnet_WSS2048T2",
"H_LIB_GER_Helmetnet_WSS40961T1",
"H_LIB_GER_Helmetnet_WSS40961T2",
"H_LIB_GER_Helmetnet_WSS40962T1",
"H_LIB_GER_Helmetnet_WSS40962T2",
"H_LIB_GER_Helmetnet_WSS40963T1",
"H_LIB_GER_Helmetnet_WSS40963T2",
"H_LIB_GER_Helmetnet_WSSCP541T1",
"H_LIB_GER_Helmetnet_WSSCP541T2",
"H_LIB_GER_Helmetnet_WSSCP542T1",
"H_LIB_GER_Helmetnet_WSSCP542T2",
"H_LIB_GER_Helmetnet_WSSg",
"H_LIB_GER_Helmetnet_WSSgc",
"H_LIB_GER_Helmetnet_WSSgcT1",
"H_LIB_GER_Helmetnet_WSSgcT2",
"H_LIB_GER_Helmetnet_WSSgd",
"H_LIB_GER_Helmetnet_WSSgdT1",
"H_LIB_GER_Helmetnet_WSSgdT2",
"H_LIB_GER_Helmetnet_WSSgT1",
"H_LIB_GER_Helmetnet_WSSgT2",
"H_LIB_GER_Helmetns_WSS1024T1",
"H_LIB_GER_Helmetns_WSS1024T2",
"H_LIB_GER_Helmetns_WSS2048T1",
"H_LIB_GER_Helmetns_WSS2048T2",
"H_LIB_GER_Helmetns_WSS40961T1",
"H_LIB_GER_Helmetns_WSS40961T2",
"H_LIB_GER_Helmetns_WSS40962T1",
"H_LIB_GER_Helmetns_WSS40962T2",
"H_LIB_GER_Helmetns_WSS40963T1",
"H_LIB_GER_Helmetns_WSS40963T2",
"H_LIB_GER_Helmetns_WSSCP541T1",
"H_LIB_GER_Helmetns_WSSCP541T2",
"H_LIB_GER_Helmetns_WSSCP542T1",
"H_LIB_GER_Helmetns_WSSCP542T2",
"H_LIB_GER_Helmetns_WSSg",
"H_LIB_GER_Helmetns_WSSgc",
"H_LIB_GER_Helmetns_WSSgcT1",
"H_LIB_GER_Helmetns_WSSgcT2",
"H_LIB_GER_Helmetns_WSSgd",
"H_LIB_GER_Helmetns_WSSgdT1",
"H_LIB_GER_Helmetns_WSSgdT2",
"H_LIB_GER_Helmetns_WSSgT1",
"H_LIB_GER_Helmetns_WSSgT2",
"H_LIB_GER_Helmetns_WSSW01T1",
"H_LIB_GER_Helmetns_WSSW01T2",
"H_LIB_GER_Helmetns_WSSW02T1",
"H_LIB_GER_Helmetns_WSSW02T2",
"H_LIB_GER_Helmetns_WSSW11T1",
"H_LIB_GER_Helmetns_WSSW11T2",
"H_LIB_GER_Helmetns_WSSW21T1",
"H_LIB_GER_Helmetns_WSSW21T2",
"H_LIB_GER_Helmetns_WSSW32T1",
"H_LIB_GER_Helmetns_WSSW32T2",
"H_LIB_GER_OfficerCap_SS",
"H_LIB_GER_OfficerCap_SS_Uffz",
"H_LIB_GER_OfficerCap_SSPZAKL",
"H_LIB_GER_OfficerCap_SSPZAKL_Uffz",
"H_LIB_GER_OfficerCap_SSPZWF",
"H_LIB_GER_OfficerCap_SSPZWF_Uffz",
"H_LIB_GER_OfficerCap_WSS",
"H_LIB_GER_OfficerCap_WSS_Bo",
"H_LIB_GER_OfficerCap_WSS_Uffz",
"H_LIB_GER_OfficerCap_WSS_Uffz_Bu",
"H_LIB_GER_OfficerCap_WSSPZAKL",
"H_LIB_GER_OfficerCap_WSSPZAKL_Bo",
"H_LIB_GER_OfficerCap_WSSPZAKL_Uffz",
"H_LIB_GER_OfficerCap_WSSPZAKL_Uffz_Bu",
"H_LIB_GER_OfficerCap_WSSPZWF",
"H_LIB_GER_OfficerCap_WSSPZWF_Bo",
"H_LIB_GER_OfficerCap_WSSPZWF_Uffz",
"H_LIB_GER_OfficerCap_WSSPZWF_Uffz_Bu",
"H_LIB_GER_TankCap_SS",
"H_LIB_GER_TankCap_WSS",
"H_LIB_GER_TankCap_WSS_Bm",
"H_LIB_GER_TankCap_WSS00",
"H_LIB_GER_TankCap_WSS03",
"H_LIB_GER_TankCap_WSS03B",
"H_LIB_GER_TankCap_WSS09",
"H_LIB_GER_TankCap_WSS15",
"H_LIB_GER_TankCap_WSS19",
"H_LIB_GER_TankCap_WSS27",
"H_LIB_GER_TankCap_WSS41",
"H_LIB_POL_Cap_WSS00A1BR",
"H_LIB_POL_Cap_WSS00A2BR",
"H_LIB_POL_HelmetCamo_WSS",
"HOL_SS_M43_Medic",
"HOL_SS_M43_MG",
"HOL_SS_M43_SecLeader",
"HOL_SS_M43_soldier_1",
"HOL_SS_M43_soldier_2",
"HOL_SS_M43_untersturmfuhrer",
"ITA_SS_M43_Medic",
"ITA_SS_M43_MG",
"ITA_SS_M43_SecLeader",
"ITA_SS_M43_soldier_1",
"ITA_SS_M43_soldier_2",
"ITA_SS_M43_untersturmfuhrer",
"LAT_SS_M43_Medic",
"LAT_SS_M43_MG",
"LAT_SS_M43_SecLeader",
"LAT_SS_M43_soldier_1",
"LAT_SS_M43_soldier_2",
"LAT_SS_M43_untersturmfuhrer",
"NOR_SS_M43_Medic",
"NOR_SS_M43_MG",
"NOR_SS_M43_SecLeader",
"NOR_SS_M43_soldier_1",
"NOR_SS_M43_soldier_2",
"NOR_SS_M43_untersturmfuhrer",
"U_LIB_GER_AT_soldier_WssFrsbrgMnnK98",
"U_LIB_GER_AT_soldier_WssFrsbrgStrmmMp40",
"U_LIB_GER_AT_soldier_WssMnn2K98",
"U_LIB_GER_AT_soldier_WssMnnK98",
"U_LIB_GER_AT_soldier_WssStrmm2Mp40",
"U_LIB_GER_AT_soldier_WssStrmmMp40",
"U_LIB_GER_Aufklr_CrewOffizier_Wss03v03pbcHstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_Wss03v03pbcUstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_Wss03v0tpbcOstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_Wss0tv0tpbcUstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_Wss0tv0tpgcOstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_Wss0tv0tpncHstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_WssFrsbrg0tv0tpbcUstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_WssFrsbrg0tv0tpgcOstufMp40",
"U_LIB_GER_Aufklr_CrewOffizier_WssFrsbrg0tv0tpncHstufMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss03v03pbcMnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss03v03pbcRttfMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss03v0spbcMnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss03v0spbcOmnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss03v0tpbcMnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss03v0tpbcStrmmMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss0tv0tpbcMnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss0tv0tpbcOmnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss0tv0tpbcStrmmMp40",
"U_LIB_GER_Aufklr_CrewPrivate_Wss0tv0tpgcRttfMp40",
"U_LIB_GER_Aufklr_CrewPrivate_WssFrsbrg0tv0tpbcMnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_WssFrsbrg0tv0tpbcOmnnMp40",
"U_LIB_GER_Aufklr_CrewPrivate_WssFrsbrg0tv0tpbcStrmmMp40",
"U_LIB_GER_Aufklr_CrewPrivate_WssFrsbrg0tv0tpgcRttfMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss03v03pbcOschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss03v03pbcStuscharfMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss03v0spbcUschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss03v0tpbcHschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss03v0tpbcScharfMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss0tv0tpbcOschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss0tv0tpbcUschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss0tv0tpgcHschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss0tv0tpgcScharfMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_Wss0tv0tpgcStuscharfMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_WssFrsbrg0tv0tpbcOschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_WssFrsbrg0tv0tpbcUschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_WssFrsbrg0tv0tpgcHschaMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_WssFrsbrg0tv0tpgcScharfMp40",
"U_LIB_GER_Aufklr_CrewUnteroffizier_WssFrsbrg0tv0tpgcStuscharfMp40",
"U_LIB_GER_medic_Wss12K98",
"U_LIB_GER_medic_WssFrsbrg00vw31p12K98",
"U_LIB_GER_medic_WssFrsbrg00vw31p13K98",
"U_LIB_GER_medic_WssFrsbrg00vw32p12K98",
"U_LIB_GER_medic_WssFrsbrg00vw32p13K98",
"U_LIB_GER_medic_WssFrsbrg12K98",
"U_LIB_GER_medic_WssFrsbrgK98",
"U_LIB_GER_medic_WssFrsbrgStrmmK98",
"U_LIB_GER_medic_WssK98",
"U_LIB_GER_medic_WssStrmmK98",
"U_LIB_GER_mgunner_Wss00v15pStrmmMg42",
"U_LIB_GER_mgunner_WssFrsbrg00v15pStrmmMg42",
"U_LIB_GER_mgunner_WssFrsbrgMnnK98Dp",
"U_LIB_GER_mgunner_WssFrsbrgMnnK98Mg42",
"U_LIB_GER_mgunner_WssFrsbrgOmnnDp",
"U_LIB_GER_mgunner_WssFrsbrgOmnnMg42",
"U_LIB_GER_mgunner_WssFrsbrgStrmmMg42",
"U_LIB_GER_mgunner_WssMnn2K98Dp",
"U_LIB_GER_mgunner_WssMnn2K98Mg42",
"U_LIB_GER_mgunner_WssMnnK98Dp",
"U_LIB_GER_mgunner_WssMnnK98Mg42",
"U_LIB_GER_mgunner_WssOmnn2Dp",
"U_LIB_GER_mgunner_WssOmnn2Mg42",
"U_LIB_GER_mgunner_WssOmnnDp",
"U_LIB_GER_mgunner_WssOmnnMg42",
"U_LIB_GER_mgunner_WssStrmm2Mg42",
"U_LIB_GER_mgunner_WssStrmmMg42",
"U_LIB_GER_ober_rifleman_WssFrsbrgOmnnG43",
"U_LIB_GER_ober_rifleman_WssFrsbrgOmnnPpsch41d",
"U_LIB_GER_ober_rifleman_WssFrsbrgOmnnPpsch41m",
"U_LIB_GER_ober_rifleman_WssFrsbrgOmnnStg44",
"U_LIB_GER_ober_rifleman_WssOmnn2G43",
"U_LIB_GER_ober_rifleman_WssOmnn2Ppsch41d",
"U_LIB_GER_ober_rifleman_WssOmnn2Ppsch41m",
"U_LIB_GER_ober_rifleman_WssOmnn2Stg44",
"U_LIB_GER_ober_rifleman_WssOmnnG43",
"U_LIB_GER_ober_rifleman_WssOmnnPpsch41d",
"U_LIB_GER_ober_rifleman_WssOmnnPpsch41m",
"U_LIB_GER_ober_rifleman_WssOmnnStg44",
"U_LIB_GER_Officer_SSBrifabP08",
"U_LIB_GER_Officer_SSBrifsbP08",
"U_LIB_GER_Officer_SSGrufabP38",
"U_LIB_GER_Officer_SSGrufsbP38",
"U_LIB_GER_Officer_SSHstufabMP40",
"U_LIB_GER_Officer_SSHstufsbMP40",
"U_LIB_GER_Officer_SSObstgrufabP38",
"U_LIB_GER_Officer_SSObstgrufsbP38",
"U_LIB_GER_Officer_SSOgrufabP08",
"U_LIB_GER_Officer_SSOgrufsbP08",
"U_LIB_GER_Officer_SSOstafabM1908",
"U_LIB_GER_Officer_SSOstafsbM1908",
"U_LIB_GER_Officer_SSOstubafabM1908",
"U_LIB_GER_Officer_SSOstubafsbM1908",
"U_LIB_GER_Officer_SSOstufabMP40",
"U_LIB_GER_Officer_SSOstufsbMP40",
"U_LIB_GER_Officer_SSStafabM1908",
"U_LIB_GER_Officer_SSStafsbM1908",
"U_LIB_GER_Officer_SSStubafabM1908",
"U_LIB_GER_Officer_SSStubafsbM1908",
"U_LIB_GER_Officer_SSUstufabMP40",
"U_LIB_GER_Officer_SSUstufsbMP40",
"U_LIB_GER_Officer_Wss03v00pOstufMp40",
"U_LIB_GER_Officer_Wss03v00pUstufMp40",
"U_LIB_GER_Officer_Wss27v00pOstufMp40",
"U_LIB_GER_Officer_Wss27v00pUstufMp40",
"U_LIB_GER_Officer_WssBrifP08",
"U_LIB_GER_Officer_WssFrsbrg03v00pOstufMp40",
"U_LIB_GER_Officer_WssFrsbrg03v00pUstufMp40",
"U_LIB_GER_Officer_WssFrsbrgBrifP08",
"U_LIB_GER_Officer_WssFrsbrgGrufP38",
"U_LIB_GER_Officer_WssFrsbrgHstufMp40",
"U_LIB_GER_Officer_WssFrsbrgOberfMp40",
"U_LIB_GER_Officer_WssFrsbrgOstubafMp40",
"U_LIB_GER_Officer_WssFrsbrgOstufMp40",
"U_LIB_GER_Officer_WssFrsbrgStafMp40",
"U_LIB_GER_Officer_WssFrsbrgStubafMp40",
"U_LIB_GER_Officer_WssFrsbrgUstufMp40",
"U_LIB_GER_Officer_WssGrufP38",
"U_LIB_GER_Officer_WssHstufMp40",
"U_LIB_GER_Officer_WssOberfMp40",
"U_LIB_GER_Officer_WssObstgrufP38",
"U_LIB_GER_Officer_WssOgrufP08",
"U_LIB_GER_Officer_WssOstubafMp40",
"U_LIB_GER_Officer_WssOstufMp40",
"U_LIB_GER_Officer_WssStafMp40",
"U_LIB_GER_Officer_WssStubafMp40",
"U_LIB_GER_Officer_WssUstufMp40",
"U_LIB_GER_PWM_soldier_WssFrsbrgOschG43",
"U_LIB_GER_PWM_soldier_WssFrsbrgStrmmMp40",
"U_LIB_GER_PWM_soldier_WssOsch2G43",
"U_LIB_GER_PWM_soldier_WssOschG43",
"U_LIB_GER_PWM_soldier_WssStrmm2Mp40",
"U_LIB_GER_PWM_soldier_WssStrmmMp40",
"U_LIB_GER_radioman_WssFrsbrgOmnnG43",
"U_LIB_GER_radioman_WssFrsbrgRttfMp40",
"U_LIB_GER_radioman_WssFrsbrgStrmmMp40",
"U_LIB_GER_radioman_WssOmnn2G43",
"U_LIB_GER_radioman_WssOmnnG43",
"U_LIB_GER_radioman_WssRttf2Mp40",
"U_LIB_GER_radioman_WssRttfMp40",
"U_LIB_GER_radioman_WssStrmm2Mp40",
"U_LIB_GER_radioman_WssStrmmMp40",
"U_LIB_GER_Rifleman_SSMnnK98",
"U_LIB_GER_Rifleman_SSOmnnG43",
"U_LIB_GER_rifleman_WssFrsbrg00v03pMnn12K98",
"U_LIB_GER_rifleman_WssFrsbrg00v09pMnn12K98",
"U_LIB_GER_rifleman_WssFrsbrg00v27pMnn12K98",
"U_LIB_GER_rifleman_WssFrsbrg00v41pMnn12K98",
"U_LIB_GER_rifleman_WssFrsbrgMnn12K98",
"U_LIB_GER_rifleman_WssFrsbrgMnnK98",
"U_LIB_GER_rifleman_WssMnn12K98",
"U_LIB_GER_rifleman_WssMnn2K98",
"U_LIB_GER_rifleman_WssMnnK98",
"U_LIB_GER_sapper_WssFrsbrgOmnnG43",
"U_LIB_GER_sapper_WssFrsbrgStrmmMp40",
"U_LIB_GER_sapper_WssOmnn2G43",
"U_LIB_GER_sapper_WssOmnnG43",
"U_LIB_GER_sapper_WssStrmm2Mp40",
"U_LIB_GER_sapper_WssStrmmMp40",
"U_LIB_GER_smgunner_WssFrsbrgRttfG43",
"U_LIB_GER_smgunner_WssFrsbrgRttfMp40",
"U_LIB_GER_smgunner_WssFrsbrgRttfPpsch41d",
"U_LIB_GER_smgunner_WssFrsbrgRttfPpsch41m",
"U_LIB_GER_smgunner_WssFrsbrgRttfStg44",
"U_LIB_GER_smgunner_WssFrsbrgStrmmG43",
"U_LIB_GER_smgunner_WssFrsbrgStrmmMp40",
"U_LIB_GER_smgunner_WssFrsbrgStrmmPpsch41d",
"U_LIB_GER_smgunner_WssFrsbrgStrmmPpsch41m",
"U_LIB_GER_smgunner_WssFrsbrgStrmmStg44",
"U_LIB_GER_smgunner_WssRttf2G43",
"U_LIB_GER_smgunner_WssRttf2Mp40",
"U_LIB_GER_smgunner_WssRttf2Ppsch41d",
"U_LIB_GER_smgunner_WssRttf2Ppsch41m",
"U_LIB_GER_smgunner_WssRttf2Stg44",
"U_LIB_GER_smgunner_WssRttfG43",
"U_LIB_GER_smgunner_WssRttfMp40",
"U_LIB_GER_smgunner_WssRttfPpsch41d",
"U_LIB_GER_smgunner_WssRttfPpsch41m",
"U_LIB_GER_smgunner_WssRttfStg44",
"U_LIB_GER_smgunner_WssStrmm2G43",
"U_LIB_GER_smgunner_WssStrmm2Mp40",
"U_LIB_GER_smgunner_WssStrmm2Ppsch41d",
"U_LIB_GER_smgunner_WssStrmm2Ppsch41m",
"U_LIB_GER_smgunner_WssStrmm2Stg44",
"U_LIB_GER_smgunner_WssStrmmG43",
"U_LIB_GER_smgunner_WssStrmmMp40",
"U_LIB_GER_smgunner_WssStrmmPpsch41d",
"U_LIB_GER_smgunner_WssStrmmPpsch41m",
"U_LIB_GER_smgunner_WssStrmmStg44",
"U_LIB_GER_sniper_WssFrsbrgUschaK98zf39",
"U_LIB_GER_sniper_WssUschaK98zf39",
"U_LIB_GER_Sturm_CrewOffizier_Wss0sv0spbcHstufMp40",
"U_LIB_GER_Sturm_CrewOffizier_Wss0sv0spbcOstufMp40",
"U_LIB_GER_Sturm_CrewOffizier_Wss0sv0spbcUstufMp40",
"U_LIB_GER_Sturm_CrewPrivate_Wss0sv0spbcMnnMp40",
"U_LIB_GER_Sturm_CrewPrivate_Wss0sv0spbcOmnnMp40",
"U_LIB_GER_Sturm_CrewPrivate_Wss0sv0spbcRttfMp40",
"U_LIB_GER_Sturm_CrewPrivate_Wss0sv0spbcStrmmMp40",
"U_LIB_GER_Sturm_CrewUnteroffizier_Wss0sv0spbcHschaMp40",
"U_LIB_GER_Sturm_CrewUnteroffizier_Wss0sv0spbcOschaMp40",
"U_LIB_GER_Sturm_CrewUnteroffizier_Wss0sv0spbcScharfMp40",
"U_LIB_GER_Sturm_CrewUnteroffizier_Wss0sv0spbcStuscharfMp40",
"U_LIB_GER_Sturm_CrewUnteroffizier_Wss0sv0spbcUschaMp40",
"U_LIB_GER_Tank_Crew_Officer_WssFrsbrg0tv0tpbcUstufMp40",
"U_LIB_GER_Tank_Crew_Officer_WssFrsbrg0tv0tpgcOstufMp40",
"U_LIB_GER_Tank_Crew_Officer_WssFrsbrg0tv0tpncHstufMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpbcMnnMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpbcOmnnMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpbcStrmmMp40",
"U_LIB_GER_Tank_Crew_Private_WssFrsbrg0tv0tpgcRttfMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpbcOschaMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpbcUschaMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpgcHschaMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpgcScharfMp40",
"U_LIB_GER_Tank_Crew_Unterofficer_WssFrsbrg0tv0tpgcStuscharfMp40",
"U_LIB_GER_Tank_CrewOffizier_Wss03v03pbcHstufMp40",
"U_LIB_GER_Tank_CrewOffizier_Wss03v03pbcUstufMp40",
"U_LIB_GER_Tank_CrewOffizier_Wss03v0tpbcOstufMp40",
"U_LIB_GER_Tank_CrewPrivate_Wss03v03pbcMnnMp40",
"U_LIB_GER_Tank_CrewPrivate_Wss03v03pbcRttfMp40",
"U_LIB_GER_Tank_CrewPrivate_Wss03v0spbcMnnMp40",
"U_LIB_GER_Tank_CrewPrivate_Wss03v0spbcOmnnMp40",
"U_LIB_GER_Tank_CrewPrivate_Wss03v0tpbcMnnMp40",
"U_LIB_GER_Tank_CrewPrivate_Wss03v0tpbcStrmmMp40",
"U_LIB_GER_Tank_CrewUnteroffizier_Wss03v03pbcOschaMp40",
"U_LIB_GER_Tank_CrewUnteroffizier_Wss03v03pbcStuscharfMp40",
"U_LIB_GER_Tank_CrewUnteroffizier_Wss03v0spbcUschaMp40",
"U_LIB_GER_Tank_CrewUnteroffizier_Wss03v0tpbcHschaMp40",
"U_LIB_GER_Tank_CrewUnteroffizier_Wss03v0tpbcScharfMp40",
"U_LIB_GER_Unterofficer_SSHschaMP40",
"U_LIB_GER_Unterofficer_SSOschaMP40",
"U_LIB_GER_Unterofficer_SSRttfMP40",
"U_LIB_GER_Unterofficer_SSScharfMP40",
"U_LIB_GER_Unterofficer_SSStrmmMP40",
"U_LIB_GER_Unterofficer_SSStuscharfMP40",
"U_LIB_GER_Unterofficer_SSUschaMP40",
"U_LIB_GER_unterofficer_Wss00v03pScharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrg00v03pScharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrg00v03pUscha12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgHscha12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgHschaMp40",
"U_LIB_GER_unterofficer_WssFrsbrgOscha12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgOschaMp40",
"U_LIB_GER_unterofficer_WssFrsbrgScharf12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgScharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrgScharfStg44",
"U_LIB_GER_unterofficer_WssFrsbrgStuscharf12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgStuscharfMp40",
"U_LIB_GER_unterofficer_WssFrsbrgUscha12Mp40",
"U_LIB_GER_unterofficer_WssFrsbrgUschaMp40",
"U_LIB_GER_unterofficer_WssFrsbrgUschaStg44",
"U_LIB_GER_unterofficer_WssHscha12Mp40",
"U_LIB_GER_unterofficer_WssHscha2Mp40",
"U_LIB_GER_unterofficer_WssHschaMp40",
"U_LIB_GER_unterofficer_WssOscha12Mp40",
"U_LIB_GER_unterofficer_WssOscha2Mp40",
"U_LIB_GER_unterofficer_WssOschaMp40",
"U_LIB_GER_unterofficer_WssScharf12Mp40",
"U_LIB_GER_unterofficer_WssScharf2Mp40",
"U_LIB_GER_unterofficer_WssScharf2Stg44",
"U_LIB_GER_unterofficer_WssScharfMp40",
"U_LIB_GER_unterofficer_WssScharfStg44",
"U_LIB_GER_unterofficer_WssStuscharf12Mp40",
"U_LIB_GER_unterofficer_WssStuscharf2Mp40",
"U_LIB_GER_unterofficer_WssStuscharfMp40",
"U_LIB_GER_unterofficer_WssUscha12Mp40",
"U_LIB_GER_unterofficer_WssUscha2Mp40",
"U_LIB_GER_unterofficer_WssUscha2Stg44",
"U_LIB_GER_unterofficer_WssUschaMp40",
"U_LIB_GER_unterofficer_WssUschaStg44",
"UKR_SS_M43_Medic",
"UKR_SS_M43_MG",
"UKR_SS_M43_SecLeader",
"UKR_SS_M43_soldier_1",
"UKR_SS_M43_soldier_2",
"UKR_SS_M43_untersturmfuhrer",
"V_LIB_GER_OfficerBelt",
"V_LIB_GER_OfficerBelt_0",
"V_LIB_GER_OfficerBeltBlack_0",
"V_LIB_GER_OfficerBeltDarkBrown_0",
"V_LIB_GER_OfficerVest",
"V_LIB_GER_OfficerVest_02",
"V_LIB_GER_OfficerVest_0A",
"V_LIB_GER_OfficerVestBlack_02",
"V_LIB_GER_OfficerVestBlack_0A",
"V_LIB_GER_PioneerVest",
"V_LIB_GER_PionierVest_0a",
"V_LIB_GER_PionierVest_3a",
"V_LIB_GER_PionierVest_4a",
"V_LIB_GER_PionierVest_5a",
"V_LIB_GER_PionierVest_6a",
"V_LIB_GER_PionierVest_7a",
"V_LIB_GER_PionierVest_8a",
"V_LIB_GER_PionierVest_9a",
"V_LIB_GER_PrivateBelt",
"V_LIB_GER_PrivateBelt_0_Luft",
"V_LIB_GER_SniperBelt",
"V_LIB_GER_SniperBelt_0a",
"V_LIB_GER_SniperBelt_0b",
"V_LIB_GER_SniperBelt_Luft",
"V_LIB_GER_TankPrivateBelt",
"V_LIB_GER_TankPrivateBelt_0",
"V_LIB_GER_Vest_Vide",
"V_LIB_GER_Vest_Vide_Luft",
"V_LIB_GER_VestG43",
"V_LIB_GER_VestG43_0a",
"V_LIB_GER_VestG43_0b",
"V_LIB_GER_VestG43_3a",
"V_LIB_GER_VestG43_4a",
"V_LIB_GER_VestG43_5a",
"V_LIB_GER_VestG43_6a",
"V_LIB_GER_VestG43_7a",
"V_LIB_GER_VestG43_8a",
"V_LIB_GER_VestG43_9a",
"V_LIB_GER_VestG43_FSJ01",
"V_LIB_GER_VestG43_FSJ02",
"V_LIB_GER_VestG43_Luft01",
"V_LIB_GER_VestG43_Luft02",
"V_LIB_GER_VestKar98",
"V_LIB_GER_VestKar98_0a",
"V_LIB_GER_VestKar98_0b",
"V_LIB_GER_VestKar98_3a",
"V_LIB_GER_VestKar98_3b",
"V_LIB_GER_VestKar98_4a",
"V_LIB_GER_VestKar98_4b",
"V_LIB_GER_VestKar98_5a",
"V_LIB_GER_VestKar98_5b",
"V_LIB_GER_VestKar98_6a",
"V_LIB_GER_VestKar98_6b",
"V_LIB_GER_VestKar98_7a",
"V_LIB_GER_VestKar98_7b",
"V_LIB_GER_VestKar98_8a",
"V_LIB_GER_VestKar98_8b",
"V_LIB_GER_VestKar98_9a",
"V_LIB_GER_VestKar98_9b",
"V_LIB_GER_VestKar98_FSJ01",
"V_LIB_GER_VestKar98_FSJ02",
"V_LIB_GER_VestKar98_Luft01",
"V_LIB_GER_VestKar98_Luft02",
"V_LIB_GER_VestMG",
"V_LIB_GER_VestMG_0a",
"V_LIB_GER_VestMG_0b",
"V_LIB_GER_VestMG_3a",
"V_LIB_GER_VestMG_3b",
"V_LIB_GER_VestMG_4a",
"V_LIB_GER_VestMG_4b",
"V_LIB_GER_VestMG_5a",
"V_LIB_GER_VestMG_5b",
"V_LIB_GER_VestMG_6a",
"V_LIB_GER_VestMG_6b",
"V_LIB_GER_VestMG_7a",
"V_LIB_GER_VestMG_7b",
"V_LIB_GER_VestMG_8a",
"V_LIB_GER_VestMG_8b",
"V_LIB_GER_VestMG_9a",
"V_LIB_GER_VestMG_9b",
"V_LIB_GER_VestMG_FSJ01",
"V_LIB_GER_VestMG_FSJ01_Medic_CBCR",
"V_LIB_GER_VestMG_FSJ01_Medic_RBCR",
"V_LIB_GER_VestMG_FSJ01b",
"V_LIB_GER_VestMG_FSJ02",
"V_LIB_GER_VestMG_FSJ02_Medic_CBCR",
"V_LIB_GER_VestMG_FSJ02_Medic_RBCR",
"V_LIB_GER_VestMG_FSJ02b",
"V_LIB_GER_VestMG_Luft01",
"V_LIB_GER_VestMG_Luft01b",
"V_LIB_GER_VestMG_Luft02",
"V_LIB_GER_VestMG_Luft02b",
"V_LIB_GER_VestMG_Medic_CBCR",
"V_LIB_GER_VestMG_Medic_RBCR",
"V_LIB_GER_VestMP40",
"V_LIB_GER_VestMP40_01",
"V_LIB_GER_VestMP40_0a",
"V_LIB_GER_VestMP40_0b",
"V_LIB_GER_VestMP40_3a",
"V_LIB_GER_VestMP40_3b",
"V_LIB_GER_VestMP40_4a",
"V_LIB_GER_VestMP40_4b",
"V_LIB_GER_VestMP40_5a",
"V_LIB_GER_VestMP40_5b",
"V_LIB_GER_VestMP40_6a",
"V_LIB_GER_VestMP40_6b",
"V_LIB_GER_VestMP40_7a",
"V_LIB_GER_VestMP40_7b",
"V_LIB_GER_VestMP40_8a",
"V_LIB_GER_VestMP40_8b",
"V_LIB_GER_VestMP40_9a",
"V_LIB_GER_VestMP40_9b",
"V_LIB_GER_VestMP40_FSJ01",
"V_LIB_GER_VestMP40_FSJ01b",
"V_LIB_GER_VestMP40_FSJ02",
"V_LIB_GER_VestMP40_FSJ02b",
"V_LIB_GER_VestMP40_Luft01",
"V_LIB_GER_VestMP40_Luft01b",
"V_LIB_GER_VestMP40_Luft02",
"V_LIB_GER_VestMP40_Luft02b",
"V_LIB_GER_VestSTG",
"V_LIB_GER_VestSTG44_01",
"V_LIB_GER_VestSTG44_0a",
"V_LIB_GER_VestSTG44_0b",
"V_LIB_GER_VestSTG44_3a",
"V_LIB_GER_VestSTG44_3b",
"V_LIB_GER_VestSTG44_4a",
"V_LIB_GER_VestSTG44_4b",
"V_LIB_GER_VestSTG44_5a",
"V_LIB_GER_VestSTG44_5b",
"V_LIB_GER_VestSTG44_6a",
"V_LIB_GER_VestSTG44_6b",
"V_LIB_GER_VestSTG44_7a",
"V_LIB_GER_VestSTG44_7b",
"V_LIB_GER_VestSTG44_8a",
"V_LIB_GER_VestSTG44_8b",
"V_LIB_GER_VestSTG44_9a",
"V_LIB_GER_VestSTG44_9b",
"V_LIB_GER_VestSTG44_FSJ01",
"V_LIB_GER_VestSTG44_FSJ01b",
"V_LIB_GER_VestSTG44_FSJ02",
"V_LIB_GER_VestSTG44_FSJ02b",
"V_LIB_GER_VestSTG44_Luft01",
"V_LIB_GER_VestSTG44_Luft01b",
"V_LIB_GER_VestSTG44_Luft02",
"V_LIB_GER_VestSTG44_Luft02b",
"WAL_SS_M43_Medic",
"WAL_SS_M43_MG",
"WAL_SS_M43_SecLeader",
"WAL_SS_M43_soldier_1",
"WAL_SS_M43_soldier_2",
"WAL_SS_M43_untersturmfuhrer"
];

GRLIB_arsenal_backpacks = [
"B_LIB_GER_A_frame",
"B_LIB_GER_A_frame_Gef",
"B_LIB_GER_A_frame_AT",
"B_LIB_BasicBag",
"B_LIB_FunkBag",
"B_LIB_GER_Backpack",
"B_LIB_GER_SapperBackpack",
"B_LIB_GER_SapperBackpack2",
"B_LIB_GER_LW_Paradrop",
"B_LIB_GER_Panzer",
"B_LIB_GER_MineBag",
"B_LIB_GER_ExplosivesBag",
"B_LIB_GER_K89AmmoBag",
"B_LIB_GER_MGAmmoBag",
"B_LIB_GER_GrenadesBag",
"B_LIB_GER_Tonister34_cowhide",
"B_Parachute",
"B_LIB_GER_A_frame_zeltbahn",
"B_LIB_GER_A_frame_kit",
"B_LIB_GER_SapperBackpack_empty",
"B_LIB_GER_Radio",
"B_LIB_GER_MedicBackpack_Empty",
"fow_b_heer_aframe",     //FoW-Mod
"fow_b_heer_ammo_belt"   //FoW-Mod
];
